- build.xml
> fixes build.xml

- build.xml
- src/bms/player/beatoraja/MainLoader.java
- src/bms/player/beatoraja/play/bga/BGImageProcessor.java
> fixes minor problem

- src/bms/player/beatoraja/PlayerResource.java
It corrects the phenomenon that preview played only once in the same songs.
> PlayerResource: detect preview*.wav(ogg) file if #PREVIEW is not set.

- src/bms/player/beatoraja/select/PreviewMusicProcessor.java
defaultMusic will fadeout under the influence of SystemVolume.
> PreviewMusicProcessor: use SystemVolume when fadeout defaultMusic

- src/bms/player/beatoraja/PlayConfigurationView.java
- src/bms/player/beatoraja/result/GradeResult.java
- src/bms/player/beatoraja/result/MusicResult.java
It fixes auto save replay conditions, and add a new condition.
> MusicResult,GradeResult: fix minor problem

- src/bms/player/beatoraja/play/JudgeManager.java
Fixed a bug that long notes are played *drrrr* during autoplay.
> Fix LN autoplay

- src/bms/player/beatoraja/play/JudgeManager.java
Fixed a bug that LN sound is not stopped when the key is released in the middle of the long note.
> Stop LN sound

- src/resources/UIResources.properties
Made an issue preventing the program from launching.
> Updated UIResources.properties file (EN)

- src/bms/player/beatoraja/play/bga/BGImageProcessor.java
- src/bms/player/beatoraja/select/MusicSelector.java
Legacy BGA (e.g. L9) will work correctly.
I think that selectedBarMoved () is necessary also when moving the slider with the mouse, so I fixed it.
> fixes drawing mistake of legacy BGA, fixes preview music problem

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
Fix crash when large video are stopped.
Large videos(e.g. 1280x720 H.265/HEVC) may crash if STOP is true when you execute code on line 106 `showingtex.draw (pixmap, 0, 0);`.
When interrupting game play and moving to the result screen, it was issuing EXCEPTION_ACCESS_VIOLATION error at the rate of about 10%.
> FFmpegProcessor: fix crash problem

- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/play/PracticeConfiguration.java
Fixed crash when player name does not exist.
It occurs when you start up without opening config at first boot.
Also fixed the problem of crashing when changing gauge type in practice.
> Fix some crash problem

- .gitignore
- beatoraja-config.bat
- build.xml
- src/bms/player/beatoraja/pattern/LaneShuffleModifier.java
- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
- src/bms/player/beatoraja/pattern/PatternModifier.java
Pattern : timeBasedShuffle method add to NoteShuffleModifier.
I changed shuffle() of case:S-RANDOM and H-RANDOM to timeBasedShuffle.
> Time based s-random

- src/bms/player/beatoraja/play/LaneRenderer.java
Fixed a bug that notes may occasionally be drawn in inappropriate modes affected by other objects.
> Fix notes drawing

- .gitignore
- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
in SP mode:
It is designed to maintain over a certain distance.
If there are more than 2 notes in the timeline, we choose randomly.
in DP mode:
Place key notes closer to scratch lane.
At that time, keep a certain distance above.
I'm sorry, 24k-DP does not correspond.
In that case, we do nothing.
> Modify ALL-SCR algorithm

- src/bms/player/beatoraja/decide/MusicDecide.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/select/MusicSelector.java
Some of the skins such as REMI-S use this timer, so I made this fix it to make it works properly.
The problem that song title is not displayed with REMI-S will be solved.
> Make STARTINPUT timer work

- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
There was a possibility of collision occurring when there were two or more Longnote destination. It solved by holding the end time.
> pattern : note shuffle corrected

- src/bms/player/beatoraja/decide/MusicDecide.java
> MusicDecide: Fix typo

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
If there are folders ending in .bms etc, I found that the program can not read the file correctly.
> SongDatabaseAccesor: Fix update of song data base

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/ControlInputProcessor.java
- src/bms/player/beatoraja/play/KeyInputProccessor.java
- src/bms/player/beatoraja/play/LaneRenderer.java
In addition, I changed it to wait a little when release the START and SELECT keys before the start of the song.
> KeyInputProcessor: Make modifiable duration by pressing SELECT + keys or scratch

- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/result/ResultKeyProperty.java
* Add `KEYBOARD_24K` and `KEYBOARD_24K_DOUBLE`.
* Avoid exceptions when `ResultKeyProperty` for the given mode is not found.
> Add 24key to ResultKeyProperty

- src/bms/player/beatoraja/play/SkinJudge.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
LR2 PMS SKINのためにNOWJUDGE_3PとNOWCOMBO_3Pを読めるようにしました。
また、index 6 (ゲージMAX時のPG)も読めるように変更しました。
> Add NOWJUDGE_3P and NOWCOMBO_3P For LR2 PMS SKIN

- src/bms/player/beatoraja/decide/MusicDecide.java
- src/bms/player/beatoraja/play/ControlInputProcessor.java
For prevent erroneous input, it needs press for more than 1 second to work.
> ControlInputProcessor: Make leave the game when press Start and Select

- src/bms/player/beatoraja/audio/PCM.java
Sorry for the confusion, I left out the command `git config user.email "your@address.com"` for the rebases and it continued to associate my commits to the wrong user!
This resolves my problem and hopefully many others when loading of songs.
> Reverting commits; PCM.java now accepts more WAV file types.

- skin/default/play9.json
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/SkinPropertyMapper.java
PMSスキンのために
- GOOD BOMB TIMER
- ゲージがボーダー以上で背景色を変化させるためのOPTION_1P_BORDER_OR_MORE
- まだ出ていない判定のジャッジカウンターを非表示にするためのOPTION_PERFECT_EXIST, OPTION_GREAT_EXIST, OPTION_GOOD_EXIST, OPTION_BAD_EXIST, OPTION_POOR_EXIST, OPTION_MISS_EXIST
を追加しました。また、被ったのでCOMBO TIMERの値を変更しました。
> Add GOOD BOMB TIMER and Several DST OPTIONs for PMSskin

- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
- src/bms/player/beatoraja/play/BMSPlayer.java
PMS時にEX-S-RANを選択することで「無理押しがなるべく来ないように配置するS-RAN」となるように変更しました。
> Add NoMurioshiSran for PMS

- src/bms/player/beatoraja/pattern/LaneShuffleModifier.java
- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
- src/bms/player/beatoraja/play/BMSPlayer.java
PMS時にEX-RANを選択することで「無理押しが来ないように配置するRANDOM」となるように変更しました。
> Add NoMurioshiRandom for PMS

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
EARLY/LATEの表示を1P2P独立で動作するようにしました。
> Modify EARLY/LATE independence

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/JudgeProperty.java
既にDiscussionにて報告されていますが、PMSの判定とSranの仕様についてPMSプレイヤー間で投票を行いました。
その内容を反映させたものです。以下は内容です。
- 基準の判定幅 COOL±20ms GREAT±50ms GOOD±117ms BAD±183ms MISS+500ms
- COOL幅はJUDGE RANKに関わらず20ms固定 
- DEFEXRANKに対応するためCOOL幅以外を係数で変動させる EASYが基準
- DEFEXRANK対応数値 VERYEASY 133 EASY（基準） 100 NORMAL 70 HARD 50 VERYHARD 33
- BAD後もGOOD以上で押し直し可
- 9keysのS乱は縦連補正無し
- 投票ログと数値イメージ https://docs.google.com/spreadsheets/d/e/2PACX-1vRH5i2t2nJ47chMpV3qel6TL-hzMAqZppqwWYzDVFXuTJEJTrm6LFEXiV5VQh3p1ScbLFyIn7vOn7hY/pubhtml
宜しくお願いします。
> Change PMS JUDGE

- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
- src/bms/player/beatoraja/play/BMSPlayer.java
PMS時にALL-SCRを選択することで「出来るだけ長い縦連打が来るように配置するS-RAN」となるように変更しました。
> Add RendaSran for PMS

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/ControlInputProcessor.java
- 14keysにおいて2P側でもHSを変更できるようにしました。
- SELECT + KeysでHSが変わる方向をSTART + Keysの方向と合わせました。
- PMS時のSELECT + Keysは全てボタン扱いとするようにしました。
> Add HS change Key for 14keys

- src/bms/player/beatoraja/play/KeyInputProccessor.java
プレイ中のターンテーブルの表示のキーを入力した時の回転方向を選曲画面での回転方向に合うようにしました。
> Modify turntable display rotation direction

- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
選曲画面において、START+SELECTでも詳細オプションを開けるようにしました。
> Add MusicSelect ShowDetailOption key(START+SELECT)

- src/bms/player/beatoraja/play/JudgeManager.java
見逃しPOOR時にキービームの色を変更しないようにしました。
> Modify KeyBeamColor when POOR

- src/bms/player/beatoraja/play/ControlInputProcessor.java
同時押しで複数段階HS変更出来るようにしました。また、Wikiに報告が上がっていた「先に鍵盤を押しっぱにしながらスタートを押すとHSが変わってしまう」のを変わらないように変更しました。
> Modify HS change key about simultaneously press

- src/bms/player/beatoraja/play/LaneRenderer.java
PMS時の見逃しPOORのノートが落ちる演出において、BPM変化と停止が同時に起こると正しく表示されない不具合があったので修正しました。
> Modify POOR noteobject movement for PMS

- src/bms/player/beatoraja/play/BMSPlayer.java
> Modify MUSIC_PROGRESS value not to exceed 1

- src/bms/player/beatoraja/play/BMSPlayer.java
ぽみゅキャラに関するタイマーを修正しました。お手数おかけしました。
> Modify POMYU chara TIMER

- src/bms/player/beatoraja/config/KeyConfiguration.java
- src/bms/player/beatoraja/decide/MusicDecide.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
- src/bms/player/beatoraja/input/KeyBoardInputProcesseor.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
additionally, add exit key support on MusicResult.
> Add enter key supports across various menus

- src/bms/player/beatoraja/select/BarRenderer.java
曲選択画面において、フォルダー最上階層で黒鍵を押すことでソート変更出来るようにしました。
> Add MusicSelect SortChangeKey(FolderClose)

- src/bms/player/beatoraja/MainController.java
スクリーンショットのファイル名に、リザルトでは「レベル 曲名 クリアタイプ ランク」、それ以外ではstate名を付加しました。
> Change Screenshot file name

- src/bms/player/beatoraja/ReplayData.java
- src/bms/player/beatoraja/play/BMSPlayer.java
プレイ画面遷移時に、3鍵でリプレイの譜面オプション再現(ランダム系は再抽選)プレイ、5鍵でリプレイのHSオプション再現プレイとなるようにしました。
> Add Replay option reproduction play

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/result/MusicResult.java
コース全体を通してのFULL COMBO、PERFECT、MAXランプを追加しました。
> Add course full combo lamp

- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
> MusicSelect: Add playing SOUND_CHANGEOPTION

- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
リプレイ自動保存以降の表示が逆になってしまっていたので修正しました。
> PlayConfigurationView.fxml: Modify AutoSaveReplay order

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinHeaderLoader.java
> Add Play Skin Offset All

- src/bms/player/beatoraja/MainState.java
- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
- src/bms/player/beatoraja/launcher/PlayConfigurationView.java
- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/skin/SkinProperty.java
It works in decide, play, result state.
If you choose from other than the difficulty table, it will be selected in Table URL list order.
通常プレイ、コースモード、フォルダ内オートプレイで一通り動作することを確認しました。
選曲画面では動作しませんが、これを選曲画面でも動かす場合
負荷を考慮するとデータベースに登録する必要性が出てきますので、この辺りで妥協しました。
> Add STRING_TABLE_NAME and STRING_TABLE_LEVEL to skin property

- src/bms/player/beatoraja/TableData.java
- src/bms/player/beatoraja/TableDataAccessor.java
難易度表のフォルダ名の表記をLEVEL xxから難易度表のSymbol/Tagを利用した表記に変更しました。
> TableData: Change folder name

- src/bms/player/beatoraja/launcher/PlayConfigurationView.java
BMSのインストールで躓く人を減らすために変更を行いました。
> PlayConfigrationView: Load automatically BMS when SongPath is added

- src/bms/player/beatoraja/MainController.java
難易度表に存在する譜面の場合、難易度表の難易度を優先してTwitterに投稿するようにしました。
> Twitter: Use tablelevel instead of playlevel if it exists

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinGraph.java
- src/bms/player/beatoraja/skin/SkinSlider.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
NUMBER値参照版スライダーとバーグラフを追加しました。
minとmaxの大小関係を逆にすることによって、NUMBER値の増減に対する動く向きを逆にすることが出来るようになっています。
> Add Skin Slider and BarGraph ReferenceNumberValue version 

- src/bms/player/beatoraja/PlayerResource.java
次の修正をしました。
- コース時に前の譜面の難易度表の情報が出てしまう問題を修正。
- 同じ譜面を再プレイした時に難易度表の情報が消えてしまう問題を修正。
> PlayerResource: Fix minor problems about Table info

- src/bms/player/beatoraja/audio/ShortPCM.java
サンプリングレート変換の際に音声スライス情報が消えるのを修正
> bug fix: Enable slicing in sample rate change

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/LaneRenderer.java
- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- mainbpm、minbpm、maxbpmのNUMBER_DURATIONを追加しました。
- currentdurationのint型へキャストするタイミングを変更しました。
- 選曲画面でもNUMBER_DURATION_GREENを使えるようにしました。
- レーンカバーがオンかどうかのOPTION_LANECOVER1_ONを追加しました。
> Add NUMBER_DURATION of mainbpm, minbpm, and maxbpm

- src/bms/player/beatoraja/MainController.java
BMSファイルの引数を与えて単曲再生すると終了時に例外が発生してプロセスが残ってしまうのを修正
> Fix termination error

- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
- src/bms/player/beatoraja/launcher/PlayConfigurationView.java
* 最新版がある場合、zipファイルへのリンクをコンフィグダイアログに追加しました。
* URL取得は非UIスレッドで動作するため、問題ないはず...
* URL及びバージョンの取得には[releases に関するGithub API](https://developer.github.com/v3/repos/releases/)を利用しています。
* ローカライズしてません(TODO)
* バージョンもうちょっと厳密に取りたいですね（現状は`MainController.VERSION.contains()`で簡易比較）
> Added link to the latest version using Github API

- src/bms/player/beatoraja/launcher/PlayConfigurationView.java
- #237 の修正をしました。
- BMSpath追加時に追加したフォルダのみを読み込むよう変更しました。
> PlayConfigurationView: fix #237 and minor improvement

- src/bms/player/beatoraja/play/BMSPlayer.java
通常段位以外で、途中落ち無しオプションがオンでも最後のノートでゲージが尽きるとゲージが切り替わらず落ちてしまっていたので、修正しました。
> Modify Continue until end of song option

- src/bms/player/beatoraja/skin/lr2/LR2SkinLoader.java
LR2SKINの「#IF」「#ELSEIF」において、負の値と「!」を使えるようにしました。
> LR2SkinLoader: Make possible to use negative value in IF or ELSEIF

- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
LR2SKINにおいて、複数の「SRC_GROOVEGAUGE」「SRC_GROOVEGAUGE_EX」を定義出来るようにしました。
> LR2PlaySkinLoader: Make possible to define multiple  SRC_GROOVEGAUGE

- folder/default.json
> Add level folder

- src/bms/player/beatoraja/config/SkinConfiguration.java
- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinHeader.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinHeaderLoader.java
CustomOptionとCustomFileの選択肢にRandomを追加しました。
> Add Random CustomOption and CustomFile

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
すみません、#253 で一か所コードを間違えていましたので修正しました。
> JSONSkinLoader: Fix Random CustomFile

- src/bms/player/beatoraja/pattern/NoteShuffleModifier.java
ALL-SCRATCHオプションで、元々スクラッチレーンにノートがある場合に連打が発生してしまう可能性がある問題を修正しました。
副作用として、鍵盤レーンがH-RANDOM仕様になりました。
> all scratch modified.

- src/bms/player/beatoraja/MainController.java
選曲画面でF2で表示されるフォルダ更新中の文字列を選曲画面でのみ表示するようにしました。
> Modify "updating folder :" display timing (only when music select)

- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
設定ダイアログのスキン設定部分でコンボボックスが操作できないのを修正
> bug fix: Combo box in skin configuration view

- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/lr2/LR2CourseResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2FontLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SelectSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
LR2SKINにおいて、Offsetを複数定義出来るようにしました。OP4の位置から改行まで任意の数で定義出来ます。
また、「DST_NOWJUDGE」と「DST_NOWCOMBO」に「OFFSET_LIFT」を追加しました。
> LR2SkinCSVLoader: Make possible to define multiple offset

- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
SkinConfigurationViewのオフセットを直接数値入力出来るようにしました。
> SkinConfigurationView: Make possible to edit offset value directly

- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/skin/SkinProperty.java
DST_OPTIONの100～105(選曲画面での選択中のバーのクリアランプ)を有効化しました。
また、1100～1104を追加分のクリアランプとしました。
> Activate DST_OPTION 100~105 (MusicSelect selected bar cleartype)

- src/bms/player/beatoraja/launcher/CourseEditorView.fxml
- src/bms/player/beatoraja/launcher/NumericSpinner.java
- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
- src/bms/player/beatoraja/launcher/VideoConfigurationView.fxml
[SpinnerのEnter押さないと値が確定しない](https://docs.oracle.com/javase/jp/8/javafx/api/javafx/scene/control/Spinner.html#editableProperty)対策で`NumericSpinner`を実装しました。
* フォーカスアウト時に`SpinnerValueFactory`に対してsetValueします。
* 最大、最小値のチェックをします。
* 例外時は`Editor`の値をもとに戻します。
散らばっていた`private <T> T getValue(Spinner<T> spinner) {}`が不要になります。
`spinner.getValue()`に統一できます。（未実施です）
***
MAXFPSを変えたのに変わらなかった現象等が改善されます。
> ConfigurationView: Using NumericSpinner

- src/bms/player/beatoraja/play/ControlInputProcessor.java
- src/bms/player/beatoraja/play/LaneRenderer.java
- src/bms/player/beatoraja/play/SkinHidden.java
プレイ中、レーンカバーがオフの場合はリフトもしくはHiddenの表示量を変更出来るようにしました。
リフトとHiddenが共にオンの場合は一応START+SELECT短押しで切り替え出来るようにしましたが、リフトとHidden併用の需要が余り無さそうなので他の機能の方が良いかもしれません。
リフトとHiddenが共にオフの場合は従来通りです。
> Make possible to change Lift or Hidden value when play

- src/bms/player/beatoraja/TableDataAccessor.java
難易度表読み込み失敗時にエラーメッセージを出力するようにしました。
> TableDataAccessor: Add error message

- src/bms/player/beatoraja/PlayModeConfig.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/LaneRenderer.java
Hidden値のセットについて漏れがあったので追加しました。
> Save Hidden change value when play end

- src/bms/player/beatoraja/play/LaneRenderer.java
> LaneRenderer: Modify getMainBPM(), MinBPM(), MaxBPM()

- src/bms/player/beatoraja/select/MusicSelectCommand.java
- src/bms/player/beatoraja/select/bar/TableBar.java
予期しないファイルのダウンロードを防ぐため、本体で指定した文字列で始まるURL以外ではIPFSによるダウンロードを中止するようにしました。
> MusicSelect: Deny download by IPFS if TableUrl is not accepted

- src/bms/player/beatoraja/play/ControlInputProcessor.java
PMS時START+8or9でレーンカバーの動く方向が直感と異なっているように感じられたのでLR2と合わせました。
> Modify LaneCover move direction when PMS

- src/bms/player/beatoraja/pattern/Randomizer.java
POPN_9Kのレーン番号ミスを修正
S-RANDOMのしきい値をゼロに修正
NoMurioshiRandomizerのアルゴリズムを修正
> refactor Randomizer with mode.POPN_9K

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/skin/SkinProperty.java
NUMBER_HIDDEN1、OPTION_LIFT1_ON、OPTION_HIDDEN1_ONを追加しました。
また、NUMBER_LIFT1とMusicResultでのNUMBER_GROOVEGAUGE_AFTERDOTを有効化しました。
> Add NUMBER_LIFT1 and NUMBER_HIDDEN1

- src/bms/player/beatoraja/PlayModeConfig.java
- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/config/KeyConfiguration.java
5keys用のキーコンフィグを追加しました。
※既知の問題点
・10keys(5鍵ダブル)は非対応
・INFコン(アナログスクラッチ)が動作しない
→PlayModeConfig.javaの307行目でBEAT_7Kのみに指定されている為
7keysとは競合しないことを確認しています
> added 5keys configuration

- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/launcher/PlayConfigurationView.java
- src/bms/player/beatoraja/play/BMSPlayer.java
プレイ中のゲージ遷移についての意見で自分が述べた案1.5です。
案1とは違い選曲画面で選択したオプションより上のクリアランプはつきません。下のクリアランプのみつきます。
> Add New GAS method (SELECT TO UNDER)

- src/bms/player/beatoraja/pattern/NewNoteShuffleModifier.java
- src/bms/player/beatoraja/pattern/Randomizer.java
リファクタリング前に合わせ、noMurioshiRandomizerのアルゴリズムを縦連回避優先から無理押し回避優先に変更しました。
可能同時押しリストの間違いを修正しました。
メソッドの可視性の変更、引数の順序変更(PatternModifier#create合わせ)、削除可能フィールドの削除を行いました。
ConvergeRandomizerの設定しきい値下限をH乱しきい値に合わせました。
> Refactor : Randomizer, NewNoteShuffleModifier

- src/bms/player/beatoraja/result/CourseResult.java
> CourseResult: Add enter key support

- src/bms/player/beatoraja/skin/PomyuCharaLoader.java
PomyuCharaLoaderにおいて、使用しない画像ファイルも透過処理を行ってしまっていたので、使用する画像ファイルのみ透過処理するようにしました。
> PomyuCharaLoader: Modify transparent processing

- src/bms/player/beatoraja/play/BMSPlayer.java
POPN_5K,9Kモードでのスクラッチ変化系ランダム無効処理を書き換えました。
> refactor: POPN_5K SCRATCH-RANDOM invalidation.

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/select/MusicSelector.java
- スコアリポジトリ等のライバルフォルダなどを難易度表として認識してしまうため、configのTableURLに含まれているか確認するように変更
- TODO スコアリポジトリ内のCollection等の機能を用いて作られた難易度表なども認識しなくなるので、必要であれば区別させる機能
- （IPFSによる楽曲ダウンロード中にコンソールに流れるメッセージを削除）
- TODO 独自Listenerを用いてメッセージ表示は実装したいところですが、まだ僕の理解が足りていないのでもう少し学習してからrenderループ内から切り離そうと思います
> Fix problem about OPTION_TABLE_SONG

- src/bms/player/beatoraja/MainState.java
- src/bms/player/beatoraja/skin/SkinProperty.java
TABLE_NAMEとTABLE_LEVELを隣同士で表示させようとした場合
TABLE_NAMEの文字が短いと文字間隔が広くなり見た目が悪くなるので
TABLE_NAMEとTABLE_LEVELを統合させたものを作りました
> SkinProperty: Add STRING_TABLE_FULL

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
ランチャーの楽曲全更新を実行する際に、楽曲のFAVORITE情報が全てリセットされてしまうため、FAVORITE情報を維持するようにしました。
> Make updateSongDatas retain favorites

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinTimingDistributionGraph.java
- src/bms/player/beatoraja/skin/SkinTimingVisualizer.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
SkinTimingVisualizerに細かい修正を加えました。
SkinTimingDistributionGraphをスキンからパラメータ設定できるようにしました。
インスタンスによらないメソッドをstaticにしました。
両スキンオブジェクトをJSONSkinに対応しました。
> modify and JSONSkin apllied : SkinTimingVisualizer, SkinTimingDistributionGraph

- src/bms/player/beatoraja/play/PracticeConfiguration.java
古いバージョンの PracticeConfiguration のデータが残っていた場合に SerializationException が発生する場合があったのを修正しました
> Handle PracticeConfiguration serialization error

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
#354 の問題で、本質的な解決には至っていませんがエラーで落ちることがないようにしました。
> FFmpegProcessor: addLast -> offerLast

- src/bms/player/beatoraja/play/JudgeProperty.java
Sorry, had to fix older revisions for some reason. This makes it so it compiles.
> fixed judgeproperty bug v2

- src/bms/player/beatoraja/play/BMSPlayer.java
プラクティス中にS-RANDOM,S-RANDOM-EXを選択するとNullPointerExceptionで落ちる問題を修正。
> bug fix : #363

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/PlayDataAccessor.java
- src/bms/player/beatoraja/select/bar/CommandBar.java
Although the location of the player path could be specified in the config file, it did not work well. I replaced the path that was still hard-coded to work.
> Hard corded player info directory path ("player") to Soft coding

- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/select/MusicSelector.java
> Enhancement: Save Sort State

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
- src/bms/player/beatoraja/audio/GdxSoundDriver.java
楽曲読み込み（主に音源ファイル）の高速化を目的としたPRです。
* 楽曲読み込み時に、音源が同じリソースをノーツごとに読んでいたのを修正しました。
* 音源読み込みを並列化しました。
* 拡張子読み込みの優先順位を変更しました。
***
音源が多いHalcyon、ノーツが多いL9999(ry、bmson形式を含むG2R2018チーム[猫箱喫茶店](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=359&event=123)のBMSにて動作を確認しています。
> Fix song loading time

- folder/default.json
folder/default.jsonにNewフォルダを追加
LAMP UPDATEなどのようにbeatoraja内部で生成した方がいいかも？
> Add new folder

- src/bms/player/beatoraja/select/MusicSelectCommand.java
- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
- src/bms/player/beatoraja/select/MusicSelector.java
START / SELECT / 5Keyでオプション開閉時のサウンドを追加しました。
オプション変更用の定数名を変更しました。
> Add option open/close sound

- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
選曲画面でコースを選択した状態で8キーを押すと、コース曲のリストが開く機能を追加
> Add display course song list

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/config/SkinConfiguration.java
> Fix skinconfig to use history

- src/bms/player/beatoraja/Config.java
デフォルト難易度表URLの以下を変更
- 24鍵SP難易度表のURLを更新
- GENOCIDE通常難易度表と発狂難易度表を追加
> Change DEFAULT_TABLEURL

- manual/hotkeys.txt
hotkeys.txtの内容が実装を反映するよう修正
https://github.com/exch-bms2/beatoraja/blob/2140b8e1094196969836db01c583debac25d264e/src/bms/player/beatoraja/play/ControlInputProcessor.java#L156-L166
> fix hotkeys.txt to match implementation

- src/bms/player/beatoraja/select/MusicSelectCommand.java
未所持のBMSでもF3キーを押すことでorg_md5属性を持っていれば該当のBMSを検索してディレクトリを表示、
持っていない場合はTitleの一部から検索を行い表示します。
> MusicSelect : open explorer when press F3 if original BMS exists

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
スキンから取得できるoptionに、コースの制約(CLASS、ゲージ、LN)を追加
> Add option CourseConstraint params

- src/bms/player/beatoraja/skin/SkinSlider.java
- src/bms/player/beatoraja/skin/json/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/json/JsonSkin.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
json/luaスキンでスライダーがマウスクリックで操作できない問題を修正
- Sliderにchangeableパラメータ(boolean)の追加。(LR2のdisableの代替)
- Typoを修正
> Fix slider in json and lua skin

- Dockerfile
Issue #495 
+ change baseImage specifying in Dockerfile
> Fix failing build jar in docker container

- src/bms/player/beatoraja/select/PreviewMusicProcessor.java
- src/bms/player/beatoraja/skin/SkinSlider.java
- Slider操作によって選曲BGMボリュームが動的に変更できない問題を修正
- Sliderを操作しても最小/最大の値(0か1)になれない問題を修正
- Sliderのangle(direction)が3(left)の時、クリック可能な範囲が実際に表示される範囲と一致していない問題を修正
> Fix volumeslider

- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/bar/GradeBar.java
Issue #503
- ブロンズ→シルバー→ゴールドの順でクリア判定を行うため、シルバーかゴールドの条件を達成していてもブロンズになる問題を修正
- ブロンズがゴールド、ゴールドがブロンズとして表示される問題を修正
> Fix trophy condition and order

- skin/default/keyconfig/keyconfigmain.lua
fix #512
デフォルトのkeyconfigスキンがdecideスキンになっていたのを修正しました
> Fix keyconfig skin

- src/bms/player/beatoraja/select/MusicSelector.java
fix 300f3cdb103f6093696abe488bd4b9ea7291035c
> Fix MusicSelector error

- src/bms/player/beatoraja/IRScoreData.java
- src/bms/player/beatoraja/play/BMSPlayer.java
現在のスコアデータはBP/ExScore/Comboの一番いい値のみをdbに保持しており、各プレイごとの値は直接出力されないと認識しています。
何らかの形でこの一回ごとのスコアを出力する機能が欲しかったため、 IRScoreData に toString() を実装し、それを log に出力する機能を追加しました。
```xml
<record>
<date>2020-04-25T15:01:35</date>
<millis>1587794495827</millis>
<sequence>31</sequence>
<logger>global</logger>
<level>INFO</level>
<class>bms.player.beatoraja.play.BMSPlayer</class>
<method>render</method>
<thread>35</thread>
<message>"score": {"Date": 0, "Playcount": 0, "Clear": 3, "Epg": 694, "Lpg": 590, "Egr": 405, "Lgr": 476, "Egd": 181, "Lgd": 214, "Ebd": 67, "Lbd": 2, "Epr": 0, "Lpr": 59, "Ems": 7, "Lms": 54, "Combo": 339, "Mode": 0, "Notes": 2688, "Clearcount": 0, "Minbp": 189, "Trophy": "", "Option": 2, "State": 0, "Sha256": "ad83ff3d3a646642c021f1fa6441b8e07eb0e70fdae4e246cadfaf5c1619b31d", "Exscore": 3449, …
```
> [FR] add logger for the current score

- src/bms/player/beatoraja/select/SearchTextField.java
fix #501
libgdx-nightly-20200611で動作を確認
> Fix FreeTypeFontGenerator of SearchtextField

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
SkinPropertyに音量表示の数値プロパティ3個追加（LR2にあったもの）
> Add volume properties

- src/bms/player/beatoraja/input/BMControllerInputProcessor.java
latest commit of beatoraja doesn't run due to ArrayIndexOutOfBoundsException
small error
> Minor fix: replace "4" with "AXIS_LENGTH" in BMControllerInputProcessor

- src/bms/player/beatoraja/pattern/LongNoteModifier.java
LongNoteを追加/削除するオプションが機能していない問題を修正
> Fix conditions of LongNoteModifier

- src/bms/player/beatoraja/play/BMSPlayer.java
クイックリトライ時にconfigが保存されていないバグが存在していましたので、動作タイミングでconfigの保存がされるように修正を行いました
お忙しいところ恐れ入りますがご確認いただければと思います
> Fix: QuickRetry(Config is not saved)

- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
OPTION_COURSE_STAGE1~4とOPTION_COURSE_STAGE_FINAL、OPTION_MODE_COURSEの実装を追加
> Add course options

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
There is a minor visual glitch in the first frame of the BGA if the same song is exited and played again.
Before the BGA plays, you will briefly see the last rendered frame of the BGA from the previous play.
It can be seen in this video:
https://user-images.githubusercontent.com/27341392/119236937-24543c00-bb75-11eb-9bdc-945986c6e7e5.mp4
Play the same song (with BGA) multiple times.
If the same song is played again, the previous FFmpegProcessor object will be reused to reduce loading time.
BGAProcessor creates a new FFmpegProcessor object.
FFmpegProcessor contains:
- `Texture showingtex;` : This variable stores the current BGA frame. [Source](https://github.com/exch-bms2/beatoraja/blob/0194a5441c0aed3dd27ad0ef5c15f58b982e0eff/src/bms/player/beatoraja/play/bga/FFmpegProcessor.java#L27)
- …
> Fix minor visual glitch with first frame of BGA

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
Hello,
While debugging why certain BMS downloads won't sound (neither bgm nor key sounds), I found out that if beatoraja had loggings about which sound file it was trying to load and whether the load resulted in null, debugging this kind of problem would have been much easier with just configuring the logging via a logging.properties file (instead of building a debuggable jar and setting breakpoints and stuff).
I'm also including the logging.properties file I used. Let me know if you think that it'll be helpful for this to also be included in the commit.
```
handlers = java.util.logging.FileHandler,java.util.logging.ConsoleHandler
.level = FINE
java.util.logging.FileHandler.level     = FINE
java.util.logging.FileHandler.encoding  = UTF-8
java.util.logging.FileHandler.append    = false …
```
> Add debug info when wav file cannot be loaded

- src/bms/player/beatoraja/select/BarRenderer.java
トロフィーの転記が漏れていました。
***
Thanks to @Albis-dev for a lot of help!
> Fix: Course creation from IRData

- src/bms/player/beatoraja/external/BMSSearchAccessor.java
- src/bms/player/beatoraja/select/BarRenderer.java
Fix #649
* とりあえず新APIに修正
* MD5が一発で取れなくなったので、APIぶん回す必要がある
* APIで取得できる単位が譜面単位ではなく楽曲単位になった
* 負荷と仕様が微妙かもなので先方と調整が必要かも？
> Fix #649 - Using new BMS Search API

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/MainLoader.java
- src/bms/player/beatoraja/config/Discord.java
- src/bms/player/beatoraja/play/BMSPlayer.java
Made changes to make Discord Rich Presence display look more natural (following [Discord RPC best practices](https://discord.com/developers/docs/rich-presence/best-practices)) and added more information:
- chart/sabun name (fulltitle instead of title)
- artist name
- time elapsed in menu/play
Old:
```
[7 Keys] Rin-Rin
```
New:
```
Rin-Rin [W] / Hyparpax
Playing: 7Keys
```
Old:
```
MUSIC SELECT
```
New:
```
In Music Select Menu
```
Old
```
RESULT
```
New
```
Result Screen
```
Currently the Discord App ID is owned by the creator of the pull request #639.
I think it may be better for the Discord App to be owned by the owner of this repository, so that changes can be made.
How to create Discord App for beatoraja:
1. Sign in to Discord at https://discord.com/developers/applications, and click …
> Discord : Improve Discord Rich Presence text

- random/default.json
- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/bar/ExecutableBar.java
フィルタされたランダムセレクトをJSONで定義できるように修正しました。  
曲周回等の利便性向上を目的としています。
***
比較(MoreThan, LessThan等)の実装は未実装。現状はイコールコンディションのみ。  
フィルタ処理はExecutableBarにやらせたいけど、Barの設計思想的に微妙かもしれない。
> Extending Random select

- .gitignore
> config_sys.jsonをUntrackedにした。

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/StringPropertyFactory.java
IRログイン時、ログインできている最初の IRPlayerData.name をSkin側で拾えるようにしました。
Result Skinでの使用を想定しています。
PROP番号は1021としましたが、適時変更ください。
> Add IR user name skin prop

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
以前 #801 の互換性問題を #805 で修正しましたが、動画の再生を中断すると次回同じ動画を再生した時に中断位置から始まるというバグが新たに発覚したため、再び修正しました。確認不足で何度も修正PRを出してしまい申し訳ありません。
中断位置から始まってしまうバグは `grabber.setFrameNumber(int)` ではなく `grabber.setVideoFrameNumber(int)` を使用すれば解決しますが、後者のメソッドはJavaCV 1.4.1で実装されたものであり、現在リポジトリのlibにあるJavaCVのバージョンでは利用できません (#805 の修正はこの互換性の解決を図るものでした)。そのため、後者の新しいメソッドの使用を試みつつ、このメソッドが未定義なら以前のループ処理 (`grabber.restart()` & `grabber.grabImage()`) を行うように変更しました。
JavaCVの更新をするという案もありましたが、無闇にlibのバイナリを更新するとリポジトリのサイズが増大するため、一旦このような解決策を採りました。ライブラリのバージョン管理方針は別途議論できればと思います。
> Fixed problem with playback position not resetting after interruption

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
- issue #812
added skin property `NUMBER_JUDGERANK` for ref id 400
> add number_judgerank skin property 

- src/bms/player/beatoraja/Config.java
(English)
Update Config.java
- replacement:NEW GENERATION Table on Normal(▽) & Insane(▼)(Old Normal 2nd & Insane 2nd)
- add overjoy(3rd)(★★)
- add Insane BMS Table(GENOCIDE/★) created by me
***
(Japanese)
デフォルト設定の難易度表を更新
- 第二通常難易度表(▽)・第二発狂難易度表(▼)のURLをNEW GENERATION難易度表の対応する表に置換え
- 第三期overjoy(★★)の追加
- 発狂BMS難易度表の追加(個人的に制作したものです
> Update default table
