exch-bms2/beatoraja

- src/bms/player/beatoraja/play/bga/BGAProcessor.java
- src/bms/player/beatoraja/play/bga/BGImageProcessor.java
It enables legacy BGI correctly.(e.g. x-aria,その欺くも美しき紅に)
The difference between the small image and the large image is the same specification as LR2.
Change the small image to the upper left justified square.
> BGImageProcessor : fixes drawing problem (fixes #19) BGAProcessor : fixes aspect ratio

- src/bms/player/beatoraja/Config.java
- src/bms/player/beatoraja/PlayConfigurationView.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/skin/SkinLoader.java
- src/bms/player/beatoraja/skin/SkinType.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
* This improves readability and extensibility in skin category distinction.
* SkinType's integral id is used to save config. This is compatible with old skin category number.
> Specify skin category by SkinType enum

- src/bms/player/beatoraja/audio/PCM.java
* There were noises caused by a bug in data conversion of 16bit sound.
* They were usually small, but sometimes very harsh if individual key sounds are loud (e.g. Papyrus / BOF2009, BMS-WAV version).
```java
pcm[i * 2] = (byte)0x9C = -100;
pcm[i * 2 + 1] = (byte)0x80 = -128;
// expected:
sample[i] = (short)0x809C = -32612;
// old:
sample[i] = (short)((int)(-100) + (int)(0x80 << 8)) = (short)((int)0x7F9C) = 32668; // harsh noise!
// new:
sample[i] = (short)((int)0x9C | (int)(0x80 << 8)) = (short)((int)0x809C) = -32612;
```
> Correct bit operation and avoid 16bit sound noise

- build.xml
The >300% decrease in size reported was probably due to the ffmpeg libraries not getting added.
> Fix compiling without adding duplicate files.

- src/bms/player/beatoraja/skin/SkinLoader.java
* Fixes a bug that note and text locations are not scaled properly when target screen size / skin resolution ratio is not integer. (For example, FullHD screen with HD skin)
> Fix skin scaling with non-integer ratio

- beatoraja-config.bat
- beatoraja-config.command
- beatoraja-config32.bat
I had to switch to Intel Series 2000 Integrated Graphics, went ahead and did some research: beatoraja performs significantly better with these _JAVA_OPTIONS properly set. I think it's a good idea to go ahead and let others know of this. My performance went from an abysmal 150-200 FPS, now to ~350-400 FPS. My computer also stopped overheating entirely after these options were enabled. 
I would test the batch scripting on your end to prevent false positives, I can't test it as I do not have access to a Windows machine at the moment.
> edited all launch scripts for potential performance increase of >20%.

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/KeyInputProccessor.java
- src/bms/player/beatoraja/play/LaneProperty.java
- src/bms/player/beatoraja/skin/SkinObject.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/SkinPropertyMapper.java
- src/bms/player/beatoraja/skin/SkinSourceImage.java
This is a preparation for extension of 24key or other modes.
* Defined new timers and values of KEY10--KEY99.
* Because existing ids and new ids are not continuous, I defined `SkinPropertyMapper` to keep codes in game logic clean.
* Using SkinPropertyMapper.
* `JudgeManager` has some mode-dependent tables describing mapping between lanes and keys, which can be used also in `KeyInputProcessor`. So I moved them to new class `LaneProperty` while generalizing them so that they are easy to extend.
* Please check that:
- key beams and bombs are appropriately displayed in each mode.
- LN, CN, HCN, BSS, etc. are appropriately judged.
- index out of range exceptions or null pointer exceptions do not occur.
* If the names of variables and methods are inappropriate, please correct them.
> Extend skin property and refactor JudgeManager and KeyInputProcessor for extension

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
- src/bms/player/beatoraja/select/MusicSelector.java
This fixes a NullPointerException that occurs on entering playing screen if any playing keys have never been pressed (i.e. using only the mouse and arrow keys to select a song).
> Set default playing device type

- src/bms/player/beatoraja/play/JudgeManager.java
Fixed a bug that excessive-pressing-poors (空POOR) around long notes are not judged
> POOR around LN

- src/bms/player/beatoraja/Config.java
- src/bms/player/beatoraja/PlayConfig.java
- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/config/KeyConfiguration.java
- src/bms/player/beatoraja/input/BMControllerInputProcessor.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
- src/bms/player/beatoraja/input/KeyBoardInputProcesseor.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/select/MusicSelector.java
This PR changes some key configuration data structure in `PlayConfig` for future extension and refactors `KeyConfiguration`.
* Keyboard: `int[] keyassign` -> new class `KeyboardConfig`.
* BM Controller: `int[] assign` -> `int[] keys`, `int start` and `int select`.
* `start` and `select` are separated from keys for extensibility.
* These changes will reset user's key configuration data (except midi) made with old versions.
> Extend key configuration

- src/bms/player/beatoraja/MainLoader.java
- src/bms/player/beatoraja/PlayConfigurationView.fxml
- src/bms/player/beatoraja/PlayConfigurationView.java
* Some devices with weird display size or aspect ratio (for example, MacBook) may reject some resolutions even if they are smaller than the display. Such resolutions should still be accepted in window mode.
* 私のMacBook Airの画面サイズ自体はHDより大きいのですが、HDのディスプレイモードに対応していないので（ウィンドウモードであっても）HDが選択できないという問題がありました。そのため、ウィンドウモードの場合は画面サイズ以下の解像度を選択できるように改善しました。
> Accept resolutions smaller than the display in window mode

- src/bms/player/beatoraja/select/BarRenderer.java
Fixed a bug that a course file may make a wrong course if `md5` or `sha256` is empty.
> Fix a bug in course construction from files in course folder

- src/bms/player/beatoraja/play/BMSPlayer.java
Device restriction in practice mode had some problems:
* When beatoraja is invoked by an external viewer with command line arguments, input is always restricted to the keyboard.
* The second and further plays in practice mode accept all devices.
So I modified the behavior to enable all devices.
`-p` 引数で起動した場合はデバイス制限のタイミングを遅らせるなどの方法も考えられますが、ややこしいですし practice mode では制限の必要性が薄いので無制限に変更しました。
> Enable all devices in practice mode

- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/KeyInputProccessor.java
* Show keybeams during autoplay
- Turntables are also rotated
* Fix a bug that key-off timers are played at the beginning of a song
----
* `JudgeManager` 内でビーム表示の処理を行うと煩雑である一方、`keystate` を直接書き換えると危険（中断時に押しっぱなしになってしまい、他の画面の操作に影響してしまうなど）なため、オートプレイ用のキー押下状態を記憶する `auto_presstime` を導入し、それを `KeyInputProcessor` から参照するようにしています。
* デフォルトスキンは、オートプレイ時の見栄えを考慮するとキービームにkey-offのアニメーションも導入したほうが良いかもしれません。
> Autoplay keybeam

- skin/default/play10.json
- skin/default/play14.json
- skin/default/play24.json
- skin/default/play24_hplus.json
- skin/default/play24_sep.json
- skin/default/play24double.json
- skin/default/play24double_hplus.json
- skin/default/play5.json
- skin/default/play5_2.json
- skin/default/play7.json
- skin/default/play7_2.json
- skin/default/play9.json
The positions of `numbers` should not be lifted by LIFT option because they are relative to the judge images.
> Fix judge number position when using LIFT

- src/bms/player/beatoraja/TableDataAccessor.java
- src/bms/player/beatoraja/select/Bar.java
* Fixed a bug that hash folders make wrong results if data does not have MD5.
* Allow `Course` to have SHA-256 as hash.
- [jbmstable-parser](https://github.com/exch-bms2/jbmstable-parser) のダウンロードしたコースデータからハッシュを取得する部分もMD5とSHA-256の両方を想定するように微修正するのが好ましいですが別件ということにします。（修正なしでも `md5` フィールドにSHA-256を格納することができるので動作上は問題ありませんが）
> Fix table accessor and music select screen for songs without MD5

- beatoraja-config.bat
ほんのちょっとした違いでしかありませんが、この2行を加えることで、beatoraja本体一式をUNCパス上、例えばNASに保存しているような特殊な環境（ちなみにウチの環境です。）、例：\\MY_NAS\BMS_software\beatoraja\~~ といったパスでも利用することができました。
※ドライブ文字を割り当ててネットワークドライブにしろよという突っ込みもあるにはあるのでしょうけど……
> for beatoraja in UNC Path (such as a NAS)

- src/bms/player/beatoraja/ClearType.java
- src/bms/player/beatoraja/CourseData.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/GaugeProperty.java
- src/bms/player/beatoraja/play/GrooveGauge.java
- src/bms/player/beatoraja/play/PracticeConfiguration.java
- src/bms/player/beatoraja/result/SkinGaugeGraphObject.java
- src/bms/player/beatoraja/select/MusicSelector.java
I added a course constraint "lr2grade".
Courses designated with this constraint will be played at the gauge of LR2.
It does not affect random options, so it is preferable to use it in combination with other constraints.
I confirmed that it was possible to play until update lamp without problems.
> GrooveGauge : add LR2 GRADE 

- src/bms/player/beatoraja/select/MusicSelector.java
On the first frame after entering a folder `getBanner` returns `null`, so we can't do `bannerbar = current` just yet.
> Fix banner not showing when entering a folder and the first song has a banner

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/LaneRenderer.java
タイマーを一度マイクロ秒で計算して誤差をなくし、1000割った数を入れるようにしました。
小節線通過でリセットもかかります。
また、autoplayやpracticeの速度変更にも対応しています。
> fix behavior for RHYTHM TIMER

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
起動時にキーコンフィグが読み込まれていなかったのを暫定修正。
TODO:前回終了時のMode参照による復元
***
Set controller config at launch. (Temporary fix)
TODO:Restoration by Mode reference at the last termination.
> [Temporary fix] Set controller config at launch.

- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
以下の3つの定義を増設しました。
SET_IMAGESET,cycle,timer,ref
SRC_IMAGESET,(null),gr,x,y,w,h,divx,divy
END_IMAGESET
また、SRC_BUTTONにも最後尾(values[15])にlenを追加してdiv分割アニメーションが使えるようにしました。lenが未記入ならば今まで通りの動作になります。
> Add imageset for LR2skin

- src/bms/player/beatoraja/play/BMSPlayerRule.java
- src/bms/player/beatoraja/play/GrooveGauge.java
* Added `KEYBOARD_24K_DOUBLE` rule.
* Avoid null gauge in `GrooveGauge.create()`.
> Fix keyboard-24k-double crashes

- src/bms/player/beatoraja/skin/SkinObject.java
I discovered that when drawing area is the same as TextureRegion, drawing becomes abnormal if Bilinear is effective. In that case I modified it to disable Bilinear.
In LITONE5, the difficulty level of the music selection screen and the background of the result screen have such symptoms.
(before)
(after)
> SkinObject: Fix rendering problem

- src/bms/player/beatoraja/audio/ASIODriver.java
- src/bms/player/beatoraja/audio/PortAudioDriver.java
Fixed a problem that stereo sounds are occasionally played incorrectly.
再生側のスレッドがループで片方のチャンネルを読み進めたタイミングで `put` が呼ばれるとその音声のステレオが反転して再生されてしまっていたので、処理順序を変更して隙が生じないようにしました。本当は `synchronized` を使うのが良いのかもしれませんが、処理の負荷が心配なのでこの変更にとどめました。 `put` 自体を複数のスレッドから呼び出したりしない限りは大丈夫なはずです。
> Fix stereo sound playback problem

- src/bms/player/beatoraja/audio/ASIODriver.java
- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
- src/bms/player/beatoraja/audio/GdxAudioDeviceDriver.java
- src/bms/player/beatoraja/audio/GdxSoundDriver.java
- src/bms/player/beatoraja/audio/PortAudioDriver.java
* Make playbacks of overloaded (defined in multiple channels) key sounds as artists expect.
同一のWAVが複数のチャンネル（定義番号）で定義されていた場合、あるチャンネルの再生時に他のチャンネルも停止していたのを修正（多重定義によるノイズ回避のテクニックが有効になるように変更）
* `stop(T id, int channel)` メソッドでは代わりにチャンネルのみ指定するということも考えられますが、それだとBMSONのスライスノーツがノイジーになるかもしれないので、音声データとチャンネルの両方が一致する音声のみ停止するようにしました。
* `GdxAudioDeviceDriver` では最近再生した有限個の音声のidを記憶しています。これは不完全な方法であり、長い音声は履歴から消えて `stop(T id, int channel)` で停止できなくなるかもしれません。それでも `stop(T id)` では停止できるのであまり支障はないと思います。（ `AbstractAudioDriver` の `stop(Note n = null)` では `stop(T id)` のほうを呼び出しているので、曲終了後など確実に停止してほしいタイミングでは停止してくれるはずです）
>  Allow key sound multi-definition

- src/bms/player/beatoraja/input/MidiInputProcessor.java
エラーが起きた時の原因と勘違いされがちだったため、正常でも表示される警告を無しにしました
> Remove excessive MIDI warnings

- src/bms/player/beatoraja/play/JudgeManager.java
空POOR判定がないときの空押しのレーザーの色を初期値に変更するようにしました。
> Change VALUE_JUDGE_KEY(laser color) when there is no judge

- skin/default/play9.json
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/SkinJudge.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- PMSプレイスキン用にコンボ表示を1列のみにするためのTIMERを追加しました。
- ゲージMAX時のPGの判定文字色を変化させるために、src/bms/player/beatoraja/play/SkinJudge.java内のjudgenowの値をゲージMAX時のPGは6とするようにしました。
- default 9keysスキンを上記仕様が反映するように変更しました。また、3PのE/Lのopの値を直しました。
> Add combo timer and Change PG value when gauge max For PMS

- src/bms/player/beatoraja/MainController.java
When is playing BMS, hides mouse cursor.
***
BMSプレイ時（`STATE_PLAYBMS`時)に、マウスカーソルを非表示にします。
BMSプレイ時にマウス操作があるのであれば、本PRの`Mouse.setGrabbed()`を利用する方法ではなく、[マウスカーソルの大きさを0として見た目上表示させないような方法](https://gist.github.com/mattdesl/4255483#file-hidecursor-java-L46)が良いと思います。
（認識していないだけかもしれませんが、現状プレイ画面でのマウス操作は無いものと思っています）
> When is playing BMS, hides mouse cursor.

- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinHeader.java
* Allow default property values in JSON skins.
* Allow custom file paths (including custom directories) for `include` command in JSON skins.
-----
* カスタムオプションでデフォルト値を指定可能にしました（構文の都合上JSONスキンのみ）。
* JSONスキンでも `include` コマンドでカスタムファイルで指定したパス（ディレクトリを含む）を使用可能にしました。
> JSON skin improvements

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- LR2スキンのDST_GROOVEGAUGEにおいて、x, y, width, height以外の値も読み込むようにしました。
- LR2スキンのEARLY/LATE付加機能にOffsetを適用するようにしました。
- BARGRAPH_MUSIC_PROGRESSを動作するようにしました。
> Modify DST_GROOVEGAUGE for LR2SKIN and Activate BARGRAPH_MUSIC_PROGRESS

- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
スキン解像度と本体設定解像度が異なる時にPMS見逃しPOORのノートの演出の消失点がズレる不具合があったので修正しました。
> Modify DST_NOTE2 for PMS LR2SKIN

- src/bms/player/beatoraja/MainState.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/ControlInputProcessor.java
- src/bms/player/beatoraja/play/JudgeAlgorithm.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/KeyInputProccessor.java
- src/bms/player/beatoraja/play/PlaySkin.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/SkinObject.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
ぽみゅキャラ(*.chp)を読めるようにしました。取り敢えずLR2SKINのみの対応です。
関連して曲終了時(STATE_FINISHED)の処理も変更しています。
また、PMS時に早MISS・早BADを出した後でも遅BADが出てしまっていたので出ないようにしました。
「曲終了時関連」
- STATE_FINISHEDからフェードアウトを開始するまでの時間をスキンで指定出来るように変更
- スタートもしくはセレクトを押しながら最後のノートが通過するとゲージがボーダー以上でもFAILEDになってしまうことがあったので、スタート・セレクト単押しでplayer.stopPlay()が発動する条件を変更
- PMS時に早MISS・早BADを出してからGOOD以上で拾わずに見逃した場合に処理済みノート数notesにカウントされていなかったので、処理済みノート数のカウント方法変更
- STATE_FINISHED時にキービームが出ないように変更
- NUMBER_TIMELEFTが負の値にならないように変更
「ぽみゅキャラ関連」
- DSTの「acc = 3：不連続」を有効化
- LR2スキン定義追加
- #FINISHMARGIN : STATE_FINISHEDからフェードアウトを開始するまでのマージン(ms)
- #DST_PM_CHARA_1P,x,y,w,h,color,offset,folderpath
- #DST_PM_CHARA_2P,x,y,w,h,color,offset,folderpath : プレイ用キャラ定義(判定連動) colorは1で1Pカラー、2で2Pカラーがあれば2Pカラーなければ1Pカラー
- #DST_PM_CHARA_ANIMATION,x,y,w,h,color,animationtype,timer,op1,op2,op3,offset, …
> Add POMYU chara loader For PMS LR2SKIN, Music end margin and Modify PMS LATE BAD

- src/bms/player/beatoraja/play/JudgeManager.java
PMS用に、LNを押した時にキービームをオフ(透明)にするために、LN時のVALUE_JUDGEの値を8となるようにしました。
> Add LongNote key beam color For PMS

- src/bms/player/beatoraja/input/BMControllerInputProcessor.java
exch-bms2/beatoraja#165
Tested on `Ubuntu 16.04`.
(I confirmed that I did not degrade on `Windows 10`.)
***
* OS判定色々ありますが今の主流って何なんですかね…
* 同様の問題がアナログじゃないコントローラでも発生しそうですが未検証です。
> fix exch-bms2/beatoraja#165 IIDX premium controller does not work on Linux

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/PlaySkin.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
元の計算式ではレーン上端が画面上端と一致しないスキンでoffset値がずれてしまうため、正確に計算できる lane region を使うようにしました。
> Use lane region to calculate offset values

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/ControlInputProcessor.java
* Practiceモードのプレイ中にハイスピの設定が利かなかったので修正
* キー処理部分をモードごとに別メソッドに分けて整理、さらに24key用の処理を追加
* Practiceモードの待機状態でハイスピ設定を可能にする修正を見越して、干渉する矢印キーの入力を無効にするメソッドを追加
> Enable HS change during play in practice mode

- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/JudgeProperty.java
window judge rateが大きい時にGOOD・BADが消える場合があったので以下の仕様に変更しました。
- window judge rateが100以下の時は従来通り
- window judge rateが100より大きい時
- PERFECT GREAT・GREATはwindow judge rate倍
- GOOD・BAD・早MISSは元の幅を維持してGREATが増えた分だけスライド
- 遅MISSは固定
また、PMS時にPERFECT GREATにExpand judgeが反映されていなかったので修正しました。
> Modify Expand judge

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/decide/MusicDecide.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/GrooveGauge.java
- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
途中落ち無しオプションがオンの時に、減少型ゲージでゲージが尽きた場合は1つ下のゲージに切り替わるようにしました。通常段位ゲージでは切り替わらずに曲の最後でFAILEDになります。
また、LR2スキンでもゲージ切り替えを出来るようにするために、JSONスキンと同じsrc分割順でEXゲージ粒まで定義出来る「SRC_GROOVEGAUGE_EX」を追加しました。
> Change gauge type when "continue until end of song option" is on

- src/bms/player/beatoraja/skin/Skin.java
- ぽみゅキャラファイル内の画像位置・サイズの定義番号において、36進数に対応しました。
- ぽみゅキャラファイル内において、ハリアイ絵のサイズを指定出来るようにするために「#CharFaceUpperSize x y w h」と「#CharFaceAllSize x y w h」を追加しました。
> Modify POMYU chara loader about CharFace size

- src/bms/player/beatoraja/config/KeyConfiguration.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
- src/bms/player/beatoraja/input/KeyBoardInputProcesseor.java
キーコンフィグにおいて、自作コントローラーなどでプレイ分のボタンしか無い場合にスタートセレクトを解除出来ないので、キーボードのDeleteで解除出来るようにしました。
追記:すみません、勘違いしてました。解除出来なくてもプレイには支障はないですね
> Add KeyConfig DeleteKey

- src/bms/player/beatoraja/MainLoader.java
* happens only when the configuration tool is not used
> fix a bug that a process is not killed after application is closed

- src/bms/player/beatoraja/play/bga/BGAProcessor.java
今まではBMSでmpgと指定されている場合mpgが優先されてロードされてしまうため、
製作者はLR2用のmpgとbeatoraja向けのmp4等を用意した場合、mp4ファイルを利用するためにはbeatoraja向けの差分などを用意する必要がありました。
この修正によって、動画ファイルに対してBMSの指定を無視して"mp4"などの拡張子を優先的にロードするようになるため、同じフォルダにmpg,mp4を用意するだけで動画ファイルが切り替わるようになります。
また、webm拡張子にも対応しました。（youtube等で使われている動画コンテナです）
>  BGAprocessor: Change priority of movie files 

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/GrooveGauge.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/result/SkinGaugeGraphObject.java
途中落ち無しオプションがオンで、コースをプレイした場合に、曲間で現在のゲージタイプの残量で全てのゲージタイプの残量が引き継がれてしまっていたので、各ゲージタイプそれぞれ別々に引き継ぐようにしました。
> Modify Change gauge type when course play

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/play/KeyInputProccessor.java
判定が出る前にキービームがオンになることがあり、判定連動キービームの場合、前の判定の色でキービームが出た後に判定が反映されて色が変わることがあったので、判定を待ってからキーオンタイマーを更新するようにしました。
> Modify Key on timer update timing

- src/bms/player/beatoraja/play/JudgeManager.java
7to9時もPG幅固定が有効になってしまっていたので修正しました。
また、スコア表示も7keys準拠になるようにしました。
> Modify 7to9 judge

- src/bms/player/beatoraja/input/KeyBoardInputProcesseor.java
マウスホイールで動く方向をLR2と合わせました。
DAOコンにはSTART+SCでマウスホイールを用いたアナログSC機能があるので、LR2と同じ方向ですと有り難いです。
> Change mouse wheel direction

- src/bms/player/beatoraja/Config.java
In some general BMS, some sounds do not sound when the simultaneous audio sources number is 64, so I changed the initial value of it to 128.
e.g. 桜シロガネ妖狐伝説
http://manbow.nothing.sh/event/event.cgi?action=More_def&num=96&event=115
> Config: Modify default number of simulataneous audio sources

- src/bms/player/beatoraja/play/BMSPlayer.java
BGAがオフの時にファイル読み込み率が50%で最大となっていたので、BGAがオフの時はBGAの読み込み率を無視するように変更しました。
> Modify Load progress value when BGA off

- src/bms/player/beatoraja/select/SearchTextField.java
曲選択画面で、曲検索後に検索結果を表示するようにしました。
また、検索結果が無い場合は、エンターキーを誤爆しないようにしました。
> MusicSelect: move to search result after search

- build.xml
- launch4j/launch4j.xml
* リリース作業用に`release`Antターゲットを作成しました。 
* releaseフォルダ内に各OSごとのzipができます。 
* Windows：exe +その他のフォルダ
* linux：jar +コマンドファイル（Mac）+その他のフォルダ
* (jarがrootに出力されるのが微妙かなと思ったので) Jarファイルの出力先を変更しました。 
* zip解凍後、起動まで確認しました (windows)  。 
* 作業フォルダ等の構造に問題がある場合は、お手数ですが修正してください。
***
* Created Ant target for release.
* It is zipped for each OS.
* Windows : exe + other folders
* linux: jar+ command file(Mac) + other folders
* Changed the output destination of the Jar file.
* I confirmed until starting (windows).
* Please correct it if there is a problem with the folder structure.
> Ant target for release

- src/bms/player/beatoraja/PixmapResourcePool.java
Fixed exception if path is not a file.
***
例：
`BMSResource.setBMSFile()`にて
```
Pixmap pix = PixmapResourcePool.loadPicture(f.getParent().resolve(model.getStagefile()).toString());
```
がありますが、`model.getStagefile()` が空の場合、フォルダパスがそのまま渡るので、`PixmapResourcePool.loadPicture()` が確定で例外(`IOException`)でした。
とりあえず、ファイルじゃなかったら読み込み処理自体を行わないようにしました。
> Suppressed exception at image loading

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java
- src/bms/player/beatoraja/skin/lr2/LR2CourseResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SelectSkinLoader.java
プレイ中に表示されているNote Distribution(TYPE_JUDGE, TYPE_EARLYLATE)においてリアルタイムで判定を反映出来るようにしました。
また、delay、背景表示の有無、判定の順序、隙間の有無をスキン側で設定出来るようにしました。
PMS時はPG=紫、GR=黄、GD=赤、BD・PR=青となるようにしました。
> Make possible to display judge distribution in real time when play

- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
ある曲を初めて演奏した時、前にプレイした別の楽曲のoldscoreが表示される問題を修正しました。
> MusicResult: Fix oldscore when played the first time

- src/bms/player/beatoraja/skin/SkinNumber.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
- LR2スキンでもLNアクティブと非アクティブを別々に定義出来るように「#SRC_LN_BODY_INACTIVE」「#SRC_LN_BODY_ACTIVE」「#SRC_HCN_BODY_INACTIVE」「#SRC_HCN_BODY_ACTIVE」を追加しました。
- 符号付き数字でも裏0を表示出来るようにしました。LR2スキンでは「#SRC_NUMBER」の14個目をzeropaddingとし、記述無しもしくは2でLR2同様裏0あり、0で裏0なしとしました。
> Add SRC_LN_BODY_ACTIVE for LR2SKIN and Signed number zeropadding

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinHeader.java
スキン未設定またはスキン読み込み失敗によりデフォルトスキンが読み込まれたときなどに、PropertyにCustomOptionが存在しないため正常に動作しない場合があるのを修正
※LR2スキンでも同様の対応が必要ですが、対応が少々面倒なのとデフォルトスキンとして読み込まれることはなく重要度は低いためとりあえず省略しています。（CustomOptionを後で追加・削除した場合を考えるとあった方がいいです）
> Enable default custom option value if the given property does not contain the option

- src/bms/player/beatoraja/select/BarRenderer.java
難易度表のフォルダを開く時に対象のモードフィルタかALLKEYSにしないと開けなかったので、フォルダを開く時は譜面が存在するモードフィルタに切り替わるようにしました。
同様の手法でモードフィルタを切り替える時も譜面が存在しないモードフィルタはスキップするようになります。
> MusicSelect: Change to mode filter which has song when folder open or mode filter change

- src/bms/player/beatoraja/MainController.java
ウィンドウモードで動作中、他のウィンドウを操作するとマウスが瞬間移動するのを修正
> Avoid mouse teleportation when switching windows

- src/bms/player/beatoraja/audio/FloatPCM.java
- src/bms/player/beatoraja/audio/ShortDirectPCM.java
- src/bms/player/beatoraja/audio/ShortPCM.java
サンプリングレート変換の際、ノイズが目立つことがある（48kHz → 44.1kHz などの場合）ので線形補間するようにしました
> improve audio resampling quality

- src/bms/player/beatoraja/play/JudgeManager.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/SkinTimingDistributionGraph.java
- src/bms/player/beatoraja/skin/SkinTimingVisualizer.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
判定タイミングの可視化グラフを追加しました。
Playスキン #SRC_TIMING_1P, #DST_TIMING_1P で直近100ノーツのタイミング、
Resultスキン #SRC_TIMINGCHART_1P, #SRC_TIMINGCHART_1P で判定タイミングの分布を表示します
それに伴い、ResultスキンにNUMBERを追加しました。
374, 375 : 平均判定タイミングズレ(整数部、小数部)
376, 377 : ズレ偏差(整数部、小数部)
> Add timing distribution thing

- src/bms/player/beatoraja/skin/lr2/LR2SkinHeaderLoader.java
LR2スキンにおいて、カスタムオプション「BGA Size」「Ghost」「Score Graph」「Judge Detail」を付加するかどうかを設定できるようにするために、「#CUSTOMOPTION_ADDITION_SETTING, BGA Size, Ghost, Score Graph, Judge Detail」を追加しました。"0"で付加しない、"0"以外で付加、です。
> Add  CUSTOMOPTION_ADDITION_SETTING for LR2SKIN

- src/bms/player/beatoraja/PlayDataAccessor.java
Double Battleなどの際トータルノーツが更新されてその後の選曲画面でのスコアレート表示がおかしくなるのを修正
> bug fix: Do not update total notes when updateScore=false

- src/bms/player/beatoraja/config/SkinConfiguration.java
> skin select screen: Select first custom file if default is not given

- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/MusicSelector.java
選曲画面において、フォルダを開いた直後やモードフィルタ・ソート変更直後、リザルトから戻ってきた直後にPlayerResourceにBMSModelがセットされていなかったので、セットするようにしました。
また、楽曲が選択されてからbmsを読み込むまでの時間はもう少し短い方が有り難いです。
> MusicSelector: Modify condition of reading bms information

- src/bms/player/beatoraja/play/BMSPlayer.java
オートプレイ時に、STATE_PRACTICE_FINISHEDを介して選曲画面に戻るとキー操作が出来なくなってしまっていたので修正しました。
> BMSPlayer: Add input.setEnable(true) in STATE_PRACTICE_FINISHED

- README.md
- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/SkinBar.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SelectSkinLoader.java
SRC_BAR_TITLE・DST_BAR_TITLEを曲バーとフォルダーバーで別々に定義したいという要望があったため、以下のようなIndexで定義出来るようにしました。
0:  通常
1:  新規
2:  SongBar(通常)
3:  SongBar(新規)
4:  FolderBar(通常)
5:  FolderBar(新規)
6:  TableBar or HashBar
7:  GradeBar(曲所持)
8:  (SongBar or GradeBar)(曲未所持)
9:  CommandBar or ContainerBar
10: SearchWordBar
3以降で定義されてなければ従来通り0:通常か1:新規が用いられます。
また、上記と関係ありませんが、README.mdに誤字を見つけたので修正しました。
> Make possible to define separately for SongBar and FolderBar in SRC_BAR_TITLE

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java
プレイ中、SkinNoteDistributionGraphを表示すると非常に重くなってしまっていたので以下の変更をしました。
- 処理済みノート数に変化があった時だけ判定分布を更新
- SkinTimingVisualizerのようにnewやdisposeはせずに透明色で埋めることで画像データをリセット
> Improve rendering speed of SkinNoteDistributionGraph when play

- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
LR2スキンにおいて、レーン上端と画面上端が一致しないスキンで、LaneRegion.heightが正しくならないので、レーンカバーのy座標の分だけ減らすようにしました。
SkinSliderのtypeは将来廃止予定とのことですが、廃止する際は変更お願い致します。
> LR2SkinLoader: Modify LaneRegion.height

- src/bms/player/beatoraja/play/SkinHidden.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
レーン下に余ったリフトカバーを覆い隠すパーツが無い場合などで「DST_HIDDEN」と同様のトリミング処理機能が欲しいという要望があったので、「SRC_LIFT」「DST_LIFT」を追加しました。
> LR2PlaySkinLoader: Add DST_LIFT

- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
各自実装した`bms.player.beatoraja.ir.IRConnection`でのExceptionや、そもそも該当メソッドが実装されていない場合にエラーとなり、`state = STATE_IR_FINISHED;` に移行しなかったのを修正しました。
***
自分の環境だと何故か例外を確認できなかったので検証いただきたいです。
> Add Exception Handling in send IR

- src/bms/player/beatoraja/MainController.java
#220 でスクリーンショットのファイル名のプレイレベルの後のスペースが消されてしまっていたので追加しました。
> Screenshot file name: Add space after PLAYLEVEL

- src/bms/player/beatoraja/play/SkinGauge.java
- src/bms/player/beatoraja/result/AbstractResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinPropertyMapper.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java
- 曲リザルトでゲージを表示出来るようにしました。starttimeとendtimeで指定してゲージが0から曲終了時の値まで増える演出をします。
- リザルトでOPTION_GAUGE_GROOVE = 42、OPTION_GAUGE_HARD = 43、OPTION_GAUGE_EX = 1046を使えるようにしました。
いずれも表示しているゲージ推移と連動します。
> MusicResult: Make possible to display GrooveGauge

- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
数字キー5で詳細オプションを出した時にDURATION_UPが使えずリプレイ切り替えとなってしまっていたので修正しました。
> MusicSelectInputProcessor: Fix about DURATION_UP cannot use when press numkey5

- src/bms/player/beatoraja/launcher/CourseEditorView.fxml
- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
- src/bms/player/beatoraja/launcher/SongDataView.fxml
以下の部分のレイアウトを改良
* 「リソース」タブのボタンサイズ
* 「プレイオプション」タブの設定内容部分をスクロールビューに格納
* 「Course」タブの各コントロールがウィンドウ拡大時に適切な大きさになるように設定
* 起動ボタンのサイズ調整
> Improve launcher view layout

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/skin/SkinProperty.java
DPのWIDEスキンなどBGA表示領域がないスキンでプラクティス設定時のみ設定メニューを表示するためにOPTION_STATE_PRACTICEを追加しました。
> SkinProperty: Add OPTION_STATE_PRACTICE

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/SkinGauge.java
- src/bms/player/beatoraja/skin/Skin.java
7to9時のゲージ粒数変更処理をリザルトでも行うためにBMSPlayerからSkinGaugeに移しました。
これは24粒ゲージだと80/100が丁度割り切れないために表示上はボーダーにのっていないにも関わらず実際には80%超えとなる場合があるので粒数を変更してます。
> SkinGauge: Move 7to9 gauge parts changing from BMSPlayer

- skin/default/play24.luaskin
- skin/default/play24main.lua
- skin/default/play_parts.lua
- src/bms/player/beatoraja/config/SkinConfiguration.java
- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinLoader.java
- src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
- src/bms/player/beatoraja/skin/lua/SkinLuaAccessor.java
* スキン全体を Lua スクリプトで記述するための機能
* Lua スクリプトが生成したテーブルを `JsonSkin` オブジェクトとして解釈し、その先は `JsonSkinLoader` に任せています
- スキンの動作中に Lua スクリプトを実行できるタイミングが増えるわけではありません（今回の拡張部分ではスキン読み込み時のみ任意コード実行できます）
- （今後の拡張も視野に入れて）スキン動作中の Lua スクリプト実行の際、読み込み時に作成したデータを利用できるようにするため、 `SkinLuaAccessor` のインスタンスはスキンごとに1個だけ生成して使い続けるようにしています（別スキン間の共有はなし）
* Lua スキンの拡張子は `.luaskin` としています（サブモジュールのluaファイルをスキンとして解釈してしまうのを回避するため）
* 例として 24key SP スキンを Lua 化
* スキン設定は Lua 側から `skin_config` 変数で参照可能
- ヘッダ読み込み時は `nil` になるので、例のように分岐して最小限の情報のみ返すのを推奨
* JSON スキンで導入した分岐や include の構文は、 JSON データから `JsonSkin` オブジェクトへのデシリアライズの段階で解釈されるため、Lua スキンが生成するテーブルの中で使うことはできません（分岐はLua の機能を使って実現することになります）
* Lua スクリプトの改善や共通部品のモジュール化は、特に問題がなければ後程行いたいと思います
> Lua skin definition support

- src/bms/player/beatoraja/launcher/PlayConfigurationView.fxml
- src/bms/player/beatoraja/select/MusicSelectCommand.java
- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
* duration の上限を5000に変更（初心者用＆24鍵モード・トリッキーなギミック譜面をプレイしやすくするため）
* 選曲画面での duration 変更をキー押しっぱなしで可能にする
* 変更間隔はとりあえず選曲バーのスクロールと同じに
* それでも大きく変更するには時間がかかるので、しばらく押し続けると10単位で変化するようにする
> Improve duration change UI

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/select/bar/DirectoryBar.java
- ライバル選択を無しにするとクラッシュする問題を修正
これに加え、次の修正を行いました
- DirectoryBar: プレイヤーのランクの計算がおかしい時、配列を超えないように修正
- MainController: updateSong thread終了時バーを更新するように
> Fix crash when rival changed

- src/bms/player/beatoraja/skin/SkinTimingDistributionGraph.java
- src/bms/player/beatoraja/skin/SkinTimingVisualizer.java
dispose処理のnullチェックに問題があったため修正しました。
プレイスキンで曲読み込み中、もしくはプラクティスで曲再生前にEscで抜けるとNullPointerExceptionがスローされる問題を修正しました。
> bug-fix :SkinTimingVisualizer#dispose

- src/bms/player/beatoraja/play/KeySoundProcessor.java
BGレーンにオブジェクトが1個も無いBMSをプレイすると例外が発生するのを修正
> Avoid index out of range error in BG lane player

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/SkinLoader.java
- src/bms/player/beatoraja/skin/SkinText.java
- src/bms/player/beatoraja/skin/SkinTextBitmap.java
- src/bms/player/beatoraja/skin/SkinTextFont.java
- src/glsl/distance_field.frag
- src/glsl/distance_field.vert
Hiero で作成した `.fnt` 形式のビットマップフォント対応
参考：[Distance field fonts · libgdx/libgdx Wiki](https://github.com/libgdx/libgdx/wiki/Distance-field-fonts)
距離フィールドは拡大してもエッジが比較的きれいで、しかもプログラムで後からアウトラインを付けたりすることもできるため、フォントテクスチャの容量削減に役立ちます。Hieroでグラデーションを使うとLR2フォントよりいい感じの結果が得られますが、距離フィールドとの併用はできないようです。
* JSON/Lua スキンのみ
* `Font` の `type` フィールドで距離フィールドフォントかどうかを設定（0:通常、1:距離フィールド）
* `Text` では以下の項目を追加で指定可能
* `wrapping` テキストの折り返し
* `overflow` 表示領域幅から溢れる場合の挙動（0:そのまま、1:縮小、2:切り詰め）
* `outlineColor`, `outlineWidth` アウトラインの色と幅（距離フィールドフォントのみ）
* `shadowColor`, `shadowOffsetX`, `shadowOffsetY`, `shadowSmoothness` シャドウ（オフセット以外は距離フィールドのみ）
* 以上のうち、 `wrapping`, `overflow`, `shadowOffsetX`, `shadowOffsetY` は従来のダイナミックフォント（`SkinTextFont`）でも使用可能になります
> Bitmap font (distance field or other prerendered fonts generated with Hiero) support

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/SkinText.java
- src/bms/player/beatoraja/skin/SkinTextBitmap.java
- src/bms/player/beatoraja/skin/SkinTextFont.java
- src/bms/player/beatoraja/skin/lua/SkinLuaAccessor.java
数値系オブジェクトと同様、Textにも `value` に Lua 式を記述できるようにしました。固定テキストをフォントで描画する用途にも使えます。（例： `value="[[example]]"` ）
> Dynamic text with Lua

- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
- src/bms/player/beatoraja/skin/lua/SkinLuaAccessor.java
#370 
* Rename conflicting setter functions for Lua
* 後で変数をテーブルに入れるなどの対応を行う可能性もありますが、とりあえず名前変更
* Handle run-time Lua exceptions
* Support Lua functions in Lua skin
* Lua スキンからは文字列でコードを渡すだけでなく、関数を直接渡すことも可能
* Example:
```lua
{id = "background", draw = "gauge() >= 75"}
```
```lua
{id = "background", draw = function()
return gauge() >= 75
end}
```
> Run-time Lua enhancement

- src/bms/player/beatoraja/play/SkinHidden.java
- src/bms/player/beatoraja/select/SkinDistributionGraph.java
- src/bms/player/beatoraja/skin/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/PomyuCharaLoader.java
- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/SkinGraph.java
- src/bms/player/beatoraja/skin/SkinImage.java
- src/bms/player/beatoraja/skin/SkinNumber.java
- src/bms/player/beatoraja/skin/SkinObject.java
- src/bms/player/beatoraja/skin/SkinSlider.java
- src/bms/player/beatoraja/skin/SkinSourceImage.java
- src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
- src/bms/player/beatoraja/skin/lua/SkinLuaAccessor.java
- src/bms/player/beatoraja/skin/property/TimerProperty.java
- src/bms/player/beatoraja/skin/property/TimerPropertyFactory.java
#370 
* Built-in timer accessors for Lua
* 例によって変数をテーブルに入れたり関数名を変更したりといった変更を行うかもしれません。
* Replace timer id with TimerProperty
* Destination と Source で参照しているタイマーをIDベースから TimerProperty に変更し、スクリプトで作成したタイマーを利用可能にしました。
* IDを指定するフィールドであった `timer` に、そのままスクリプト（文字列）または関数を渡せるようになっています。
* `value` や `draw` などはID指定とは別フィールドになっていたので、`timer` とは別に関数用のフィールドを新しく作るかどうか迷いましたが、`JsonSkinLoader` 内の処理が非常に煩雑になってしまうのを避けるためまとめました。
* 逆に、 `value` などに文字列や関数ではなく数値を指定すると参照IDとして解釈するようにしました。（`ref` とか `op` に関数を渡せるように拡張するのは名前的に不自然ですが、こちらの方向であればそれほど不自然ではないため）
* 一部タイマーIDに依存した処理を行っていた箇所があるため、ID指定のタイマーは後からIDを取得できるように特殊対応
* タイマーの書き方の例
```lua
timer = 46 -- 従来のID指定
timer = "timer(46)" -- スクリプト文字列
timer = function()  -- 関数
return timer(46)
end
```
* 複雑なタイマーの例
```lua
-- タイマーID id1, id2 が両方アクティブなときにONになるタイマー
function both_active(id1, …
```
> Lua timer definition support

- src/bms/player/beatoraja/config/SkinConfiguration.java
ゲーム中のスキン設定画面でスキンの存在しない項目を選択するとぬるぽで落ちるのを修正
> SkinConfiguration: fix NullPointerException

- src/bms/player/beatoraja/config/SkinConfiguration.java
- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
- src/bms/player/beatoraja/skin/SkinLoader.java
- src/bms/player/beatoraja/skin/json/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/json/JsonSkin.java
- src/bms/player/beatoraja/skin/json/JsonSkinSerializer.java
- src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
関連クラスをスキンオブジェクトの作成処理、JSONスキン仕様クラス、JSONシリアライザの3つに移動・分割しました。
* `bms.player.beatoraja.skin.JSONSkinLoader` の本体部分（オブジェクト作成処理） → `bms.player.beatoraja.skin.json.JSONSkinLoader`
* `bms.player.beatoraja.skin.JSONSkinLoader` のシリアライザ部分 → `bms.player.beatoraja.skin.json.JsonSkinSerializer`
* `bms.player.beatoraja.skin.JSONSkinLoader.JsonSkin` → `bms.player.beatoraja.skin.json.JsonSkin.Skin`
* `bms.player.beatoraja.skin.JSONSkinLoader.*` → `bms.player.beatoraja.skin.json.JsonSkin.*`
本体部分の巨大なロード関数 `loadJsonSkin` の分割は今後の課題です。
> Refactor JSON skin loader (move classes)

- src/bms/player/beatoraja/skin/SkinImage.java
- src/bms/player/beatoraja/skin/json/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/json/JsonSkin.java
ImageSet の参照画像選択用 IntegerProperty にLuaスクリプトを設定できるようにしました。Value（number）と同様、`ref` とは別のフィールド `value` を読むようにしています。
> Accept lua value in ImageSet

- src/bms/player/beatoraja/play/SkinGauge.java
SkinGaugeの直前で色付きのオブジェクトを描画しているとゲージが変色するのを修正
> Skin Gauge: fix color bug

- src/bms/player/beatoraja/skin/json/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/lua/EventUtility.java
- src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
- src/bms/player/beatoraja/skin/lua/MainStateAccessor.java
- src/bms/player/beatoraja/skin/lua/SkinLuaAccessor.java
- src/bms/player/beatoraja/skin/lua/TimerUtility.java
#370 
「現在ある問題点」の2つ目、Luaに公開する関数がグローバル変数に置かれている（のでLuaスキンから使いにくい）という問題に以下のように対処しました。
* JSONスキンでは `value` などに書いたLuaスクリプト内部で変数を作成することが少なく、名前衝突を回避する必要があまりないため、短く書けることを重視してグローバル変数として公開
* Luaスキンでは、上記issueで書いているように単にテーブルに格納するよりも、`require` で読み込めるライブラリのような形で提供するのが良いと考え、`package.loaded` にテーブルを追加
* スキン設定を提供するグローバル変数 `skin_config` については、ライブラリというよりもLuaプログラムの引数のような役割であることと、ヘッダ読み込みかどうかの判定（`if skin_config then ...`）のしやすさを考慮してグローバル変数のままにしています
スキン側で必要な対応は以下の通りになります。（デフォルトスキンでは対応の必要な箇所なし）
* JSONスキンはそのままでOK
* Luaスキンで `timer` などの関数を使っている場合は以下のように変更
```Lua
-- main_state モジュールを読み込む（最初に書く）
local main_state = require("main_state")
...
-- local t = timer(id)                         -- 変更前
local t = main_state.timer(id)                 -- 変更後
```
また、カスタムイベントやカスタムタイマーを作成するための便利関数を `main_state` とは別のモジュールに公開しています。
* …
> Move Lua accessors to modules, and add new functions

- src/bms/player/beatoraja/play/PracticeConfiguration.java
- src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java
If FREQ != 100, the position of the cursor line in the note distribution graph is wrong.
This happens in practice mode.
> Fix issue with wrong position of cursor line in practice mode when freq != 100

- src/bms/player/beatoraja/play/GrooveGauge.java
120.0 <= total < 130.0 should do 3.333x damage, not 33.33x damage
http://2nd.geocities.jp/yoshi_65c816/bms/LR2.html
> Fix error in LR2 hard gauge damage code

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
- NUMBER_DENSITY_ENDPEAKの返す値がdensity(平均密度)だったため、意味に相違がないように名前をNUMBER_DENSITY_AVERAGEに変更
- NUMBER_DENSITY_END(ラスト密度)とNUMBER_DENSITY_PEAK(最高密度)もスキンで取得できるよう追加
> Fix and add density numbers

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
1曲の中でスライスあり・なしの両方使われている音源が存在するとき正しく再生されないのを修正しました。
例：Goliath（任意の譜面）
> Fix BMSON sliced sounds

- src/bms/player/beatoraja/audio/GdxSoundDriver.java
[Drop Down[A]](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=189&event=116)をプレイしようとして発見したバグへの修正です。
#WAV宣言内の拡張子が大文字でも読み込めるようにしました。
> fix loading key sound files of upper case extension

- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/PracticeConfiguration.java
プラクティスの表示を一部拡張しました。
* ノーツグラフ表示部分をJUDGE/EARLY-LATEで切り替えられるようにし、最終プレー結果を参照できるようにしました。
* 最終プレー結果の判定結果を表示するようにしました（右側）
* ついでに、プラクティスプレー時、判定グラフが最初のプレーのみしか反映されない（プレーごとにリセットされない）のを修正しました。
> Add note graph shift with practice.

- src/bms/player/beatoraja/PlayDataAccessor.java
**Bug:** for player2, player3 etc, replay folder is not correctly created.
beatoraja creates `./replay` folder instead, which is wrong and is always empty.
player1/replay is created on beatoraja first startup, so no issue occurs with player1
but player2, player3 etc cannot save replays, unless the replay folder is manually created by the user.
> Fix bug: replays not working for player2, player3 etc..

- src/bms/player/beatoraja/launcher/CourseEditorView.java
**Bug**:
1. open course tab in beatoraja config
2. create course "ABC", no constraints.
3. create course "DEF", add some constraints (e.g. CLASS, GAUGE_LR2)
4. if you click "DEF", then "ABC", the constraints will be copied over to ABC automatically. (should not happen, because ABC course constraints should be "null").
This fix makes it so that "null" constraints do not get overwritten by other courses.
> Fix course constraint 'null' being overwritten in course creation config

- src/bms/player/beatoraja/select/MusicSelector.java
難易度表の譜面で8キーでSameFolderBarを開いて選曲した際に、どの譜面でも難易度表の名前とレベルが同じになる問題を修正。
> Fix tablename and tablelevel when SameFolder

- src/bms/player/beatoraja/play/JudgeProperty.java
If EXPAND JUDGE < 100, it is not possible to get PGREAT or GREAT unless you hit `+0ms`.
(everything will be GOOD)
Because it's the same as setting EXPAND JUDGE = 0.
EXPAND JUDGE = 199 is the same as EXPAND JUDGE = 100,
EXPAND JUDGE = 299 is the same as EXPAND JUDGE = 200, etc etc
JudgeProperty refactor (commit 10488d98eb4743d928990890fb210ec57df79d3e) caused this problem with this line:
```
judge[i][j] *= judgeWindowRate / 100;
```
(`judgeWindowRate = 99` becomes `judge[i][j] *= 0`)
> Fix EXPAND JUDGE not working when EXPAND JUDGE < 100.

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
- src/bms/player/beatoraja/play/bga/BGAProcessor.java
- src/bms/player/beatoraja/select/PreviewMusicProcessor.java
[Path resolve(String other)](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#resolve(java.lang.String)) will throw an InvalidPathException if `other` has invalid characters like `?`.
Example: `path.resolve("???.png")` throws an exception, can crash beatoraja.
`Path resolve(String other)` is used in many places in the code.
1. **BGAProcessor** (BGA issue)
- If `#BMP01` is set to `???.png`, beatoraja will crash.
2. **AbstractAudioDriver** (Keysound issue)
- If `#WAVxx` is set to `???.wav`, beatoraja will crash.
3. **PreviewMusicProcessor** (Preview issue)
- If `#PREVIEW` is set to `???.wav`, beatoraja will crash.
I think there may be other places where `Path resolve(String other)` is used.
I only fixed the most important locations.
Sample 差分 x3 that will crash beatoraja: …
> Fix beatoraja crash when path.resolve() is called with file name = ???

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
1. Use LITONE5 skin for MUSIC SELECT, use `Blue&Green Full of Stars.mp4` for movie background.
- The other two mp4 movie backgrounds also work. But some other videos won't cause the crash.
2. Start playing a song.
3. Exit the song before the first note.
4. During exit, hold KEY 1 so that the song will restart immediately after returning to MUSIC SELECT.
5. When song is started again, beatoraja will crash with `EXCEPTION_ACCESS_VIOLATION (0xc0000005)`
1. This code runs with a delay:
```java
Gdx.app.postRunnable(() -> {
final Pixmap p = pixmap;
if (p == null) {
return;
}
if (showingtex != null) {
showingtex.draw(p, 0, 0);
} else {
showingtex = new Texture(p);
}
});
```
2. When song is started, `showingtex.dispose()` is called. (because `SkinSourceMovie` calls `dispose()` on …
> Fix FFmpegProcessor crash when song is restarted too quickly

- src/bms/player/beatoraja/IRScoreData.java
- src/bms/player/beatoraja/PlayDataAccessor.java
- src/bms/player/beatoraja/ScoreDataProperty.java
- src/bms/player/beatoraja/ScoreDatabaseAccessor.java
- src/bms/player/beatoraja/play/BMSPlayer.java
- src/bms/player/beatoraja/play/JudgeManager.java
This implementation solves #340 for local best ghosts.
A Judgment sequence is encoded into a string with GZIP and Base64Url. Example: `1,1,0,2,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,1,1,0,0,0,...` (~900 notes) → `H4sIAAAAAAAAAF1TCRKEMAgjGf__5rU0CbjVmR4COahAEU...` (~300 characters)
The ghost corresponding to the best score is saved in `ghost` column of `score` table. So they are independent of replay data. If no ghost exists, the score graph goes at the linear speed.
IR ghosts may be available if `IRConnection` implementations uses `IRScoreData.ghost`.
The ghost is playbacked only if the actual total notes is equal to the recorded total notes. Otherwise, the score graph goes at the linear speed.
The order of judgments may be interchanged around long notes. This implementation do not care …
> Record and use player ghosts

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
1. Find a song with BGA
2. Play song with BGA ON. exit song.
3. Turn off BGA and play the song again. beatoraja will crash.
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
at bms.player.beatoraja.play.bga.FFmpegProcessor.stop(FFmpegProcessor.java:66)
at bms.player.beatoraja.play.bga.BGAProcessor.prepare(BGAProcessor.java:219)
at bms.player.beatoraja.play.BMSPlayer.render(BMSPlayer.java:424)
at bms.player.beatoraja.MainController.render(MainController.java:395)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```
BGAProcessor continues to hold a pointer to FFmpegProcessor after FFmpegProcessor is disposed.
When `stop()` is called after …
> Fix crash when BGA is turned off - NullPointerException in FFmpegProcessor

- src/bms/player/beatoraja/play/bga/BGAProcessor.java
Depending on choice of SONG A, beatoraja may crash.
1. Find song with BGA. **[SONG A]**
2. Start song and wait until BGA starts playing.
3. Exit song.
4. Find a different song with BGA **[SONG B]**
5. Start song, and exit song before song starts.
You might see the song's BGA flash on the screen before the song exits.
This is only a visual issue - not a serious error.
However, if **[SONG A]**'s BGA is made from many images (example: FREEDOM DIVE), this will cause beatoraja to crash after step 5.
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 258
at bms.player.beatoraja.play.bga.BGAProcessor.getBGAData(BGAProcessor.java:234)
at bms.player.beatoraja.play.bga.BGAProcessor.drawBGA(BGAProcessor.java:312)
at …
```
> Fix ArrayIndexOutOfBoundsException in BGAProcessor when song is started

- src/bms/player/beatoraja/play/ControlInputProcessor.java
When playing a song, lane cover / green number adjustment controls do not work in 5K and 10K mode.
In 7K / 14K mode, in the `key[]` array,
- 0,1,2,3,4,5,6 = buttons
- 7,8 = turntable
- 9,10,11,12,13,14,15 = buttons
- 16,17 = turntable
But for 5K / 10K mode,
- 0,1,2,3,4 = buttons
- 5,6 = turntable
- 7,8,9,10,11 = buttons
- 12,13 = turntable
When holding START or SELECT, 5K / 10K mode uses 7K / 14K controls, so keys **7,8,16,17** are still used for adjustment. So the turntable cannot move the lane cover / change green number.
Create new functions `processStart5key()` and `processSelect5key()` used for 5K/10K modes.
And in these functions, the turntable is **5,6,12,13**.
> Fix lane cover/green number adjustment in 5K/10K mode

- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
- ランダムセレクトバーを表示する条件を、フォルダ内に1譜面以上から2譜面以上に変更
- SkinPropertyにランダムセレクトバーを判別するためのオプション(OPTION_RANDOMSELECTBAR)を追加
- ランダムセレクトバーを選択中に、OPTION_PLAYABLEBARがtrueを返すよう変更
> Improve randomselect

- src/bms/player/beatoraja/result/SkinGaugeGraphObject.java
SkinGaugeGraphObject描画時にRGB値がリセットされるように、drawメソッドの使用をSkinObjectRendererからSkinObjectに変更しました。それに合わせてbacktexの型をTextureからTextureRegionに変更しました。
> Modified to use protected method(SkinObject#draw).

- src/bms/player/beatoraja/skin/SkinTextBitmap.java
Beatoraja 0.7.4 with LITONE6 or LITONE7, bitmap fonts are not able to be loaded. Just to initialize `SkinTextBitmap` once with constructor will be fine to load it properly.
> Fix Bitmap Font not loaded

- README.md
Only the 6th row of Features, `Various assist options : legacy note, expand judge, bpm guide, and no mine` is capitalized. I think it should be unified.
> Uncapitalize the 6th row of Features in README

- src/bms/player/beatoraja/select/MusicSelectInputProcessor.java
SameFolderBarのTitleを譜面のTitleからFullTitleに変更
- SUBTITLEが存在する譜面からSameFolderBarを開くと、開いた位置に戻れない問題を修正するため
> Change SameFolderBar title to fullTitle

- src/bms/player/beatoraja/ScoreDataProperty.java
14316ノーツ以上のBMSで20万点スコアがオーバーフローする問題を修正
> Fix score overflow

- src/bms/player/beatoraja/launcher/ControllerConfigViewModel.java
- src/bms/player/beatoraja/launcher/InputConfigurationView.fxml
- src/bms/player/beatoraja/launcher/InputConfigurationView.java
- src/bms/player/beatoraja/launcher/SpinnerCell.java
プレイサイドごと（コントローラーごと）にスクラッチ周りの設定をできるようにしました。
例：14KEYでアナログスクラッチを設定した場合、10KEYの同じデバイスにアナログスクラッチの設定が展開されない
> Fix analog scr setting

- src/bms/player/beatoraja/skin/SkinText.java
- src/bms/player/beatoraja/skin/json/JSONSkinLoader.java
- src/bms/player/beatoraja/skin/json/JsonSkin.java
json、luaスキンのtext定義にconstantTextパラメータを追加
- String型
- 任意の文字列を指定可能
- refパラメータが指定されている場合はrefが優先され、constantTextは無視される
意図
- 画像を用意するほどでもない簡単な任意のテキストをtext定義だけで作れるようになります
> Add constantText to SkinText

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
シングルクオート(')を含む文字列での譜面検索が失敗する(シングルクオート2つ('')に置換されてしまう)問題を修正
> Fix to search for single quote

- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/select/SearchTextField.java
- 検索窓に空文字が入力された状態でEnterを入力した時に、"検索"と"曲/フォルダ選択"の2回アクションが実行される問題を修正。
- 検索窓にフォーカスしている(カーソルがある)状態で、検索窓の外をクリックするとフォーカスが外れるよう変更。
- 検索窓にフォーカスしている(カーソルがある)状態で、Stateが変わる(画面遷移する)とフォーカスが外れるよう変更。
- 選曲スキンを変更した時に、検索窓の位置が更新されない問題を修正。
> Fix searchtextfield

- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
I think the skin property NUMBER_MAXSCORE should be `getNotes() * 2`
Please review this change. If this is wrong, reject this pull request.
> Change NUMBER_MAXSCORE to getNotes() * 2

- src/bms/player/beatoraja/skin/BitmapFontCache.java
- src/bms/player/beatoraja/skin/SkinTextBitmap.java
Hacky workaround to reduce loading times when using skins with bitmap fonts.
- [Play to music select](https://streamable.com/hiemgi)
- [Music select to play](https://streamable.com/9j087i)
> Implement additional caching for bitmap fonts.

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
songdata.dbのsongテーブルのprimary keyをpathのみに変更
pathが同じまま譜面内容を更新した(sha256が変わった)場合に、songテーブルのprimary keyが`sha256`と`path`の2つであることで、楽曲更新時に`INSERT OR REPLACE`のREPLACE処理が実行されず、同じpathで異なるsha256を持つレコード2つが同時に存在できてしまっていた。
songテーブルの`sha256`カラムがprimary keyである必要はないので、楽曲更新時のREPLACEを正しく実行させるために、songテーブルのprimary keyを`path`のみに変更した。
> Change primarykey of  songdata.db song table

- src/bms/player/beatoraja/skin/SkinBPMGraph.java
最終ノーツ後にBPMオブジェが配置されている譜面で、BPMグラフとノーツ分布グラフの長さが同期されず、正常に表示されない問題を修正。
例: Andro [ANOTHER]
before
after
> Fix SkinBPMGraph lastTime

- src/bms/player/beatoraja/select/BarRenderer.java
選曲画面でフォルダを閉じた時に、フォルダを開く元となったバーにカーソルが合うように、フォルダを開く元となったバーを保字するキュー`sourcebars`を追加。
> Add sourcebars to improve folder close

- src/bms/player/beatoraja/select/MusicSelector.java
曲検索フィールドが無い選曲スキンを使用中に、選曲画面からスキン選択画面などの別ステートに遷移すると、NPEが発生するバグを修正
> Fix NPE in MusicSelector

- src/bms/player/beatoraja/play/bga/BGAProcessor.java
#BMPxxで定義されているファイル名と一致する動画ファイルが存在しなかった場合の拡張子補完で、優先順位が画像拡張子>動画拡張子だったのを動画拡張子>画像拡張子になるよう修正。
例: 定義がbga.mpgで同梱がbga.mp4とbga.pngの場合
- 変更前: bga.pngが使用される
- 変更後: bga.mp4が使用される
> Fix bga extension complement

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
#VOLWAVが設定されている譜面をプレイすると、それ以降の#VOLWAVが設定されていない譜面のプレイ時音量にも#VOLWAVが適用されたままになる問題を修正。
情報元: https://hitkey.nekokan.dyndns.info/diary2012.php#D201222
> Fix continuation of #VOLWAV

- src/bms/player/beatoraja/play/BMSPlayer.java
クイックリトライ機能の追加です
プレイ終了時にリザルトを通さずにリトライすることができます(データは保存されません)
スタートボタンを押すとランダムは再配置され、セレクトボタンを押すと先ほどと同じ譜面となります
強制終了を行った場合は、強制終了の操作終了後にスタートもしくはセレクトを押す必要があります
また、リトライ時に暴発して強制的にプレイ終了にならない様に、スタートとセレクト同時押しした場合は反応しないようになっています
動画はノーマルリトライ->クイックリトライの順で実行しております
ご検討いただけますと幸いです。
https://user-images.githubusercontent.com/77520794/105019007-f8229480-5a88-11eb-9635-b119569ca11f.mp4
> Add : quickretry (クイックリトライ機能の追加)

- src/bms/player/beatoraja/launcher/MusicSelectConfigurationView.fxml
In commit 283060b5c6e294b7dde0274122a089d2c4d6cde9, `CheckBox playPreview` is replaced with `ComboBox<SongPreview> songPreview` in **MusicSelectConfigurationView.java**, but it is not replaced in **MusicSelectConfigurationView.fxml**.
This will cause a NullPointerException in MusicSelectConfigurationView when the beatoraja config is opened.
This pull request adds the ComboBox to MusicSelectConfigurationView.fxml. Please modify as appropriate.
> Fix NullPointerException from missing songPreview ComboBox

- src/bms/player/beatoraja/play/TargetProperty.java
Calculated target scores would always be off by a few points previously, this replaces the current values with more accurate ones.
> fix inaccurate pacemaker values

- src/bms/player/beatoraja/input/BMControllerInputProcessor.java
Analog Scroll turntable direction is reversed.
Analog Scroll ON and Analog Scroll OFF makes the turntable go in opposite directions.
Analog Scroll OFF direction is correct. So we flip Analog Scroll ON's direction.
> Analog Scroll Hotfix 1 : Reversed Direction

- src/bms/player/beatoraja/input/BMControllerInputProcessor.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
- src/bms/player/beatoraja/input/KeyBoardInputProcesseor.java
- src/bms/player/beatoraja/input/MidiInputProcessor.java
There have been many reports recently of strange behavior in beatoraja when multiple controllers are detected.
There are two main problems, and there are 3 effects. Both problems contribute to both effects.
**Current testers:** me (using YuanCon + 2x vjoy virtual joystick), Telperion (using DAO Real Edition Double)
Plugging in an additional controller may turn off Analog Scroll (For example, Controller 2 may turn off Analog Scroll for Controller 1)
Video: https://clips.twitch.tv/FreezingBelovedWombatNerfRedBlaster-NrJxFc0o1VVLSYGC
- Turn on analog scroll and analog scratch.
- Have two controllers plugged in. Controller 2 can be any type of controller (e.g. xbox 360 controller).
- Now try to turn the turntable during music select.
Plugging in an additional controller may cause weird …
> Analog Scroll Hotfix 2 : Multiple Controllers

- src/bms/player/beatoraja/launcher/SkinConfigurationView.java
ランチャーのスキンタブでのSkinConfigの編集内容を、起動/終了ボタンのクリック時(`commit()`呼び出し時)にskinHistoryに保存するように変更。
これにより、以下のSkinConfigの編集内容が保存されない現象が解消します。
1. ランチャーのスキンタブでSkinConfigを編集する
2. スキン種類やスキンの切り替えを行わずにbeatorajaを起動する
3. F12でスキンコンフィグ画面を開く
4. スキンコンフィグ画面に1で編集した内容が反映されていない
beatoraja内のスキンコンフィグ画面(`SkinConfiguration`)では、SkinConfigはskinHistoryから呼び出す。
ランチャーのスキンタブでは、スキン種類orスキンの切り替えでSkinHistoryが保存される。
しかしランチャーの起動/終了ボタンクリック時にはskinHistoryが保存されない。
そのため、ランチャーでSkinConfig編集後にそのまま起動ボタンでbeatorajaを起動してスキンコンフィグ画面を開くと、ランチャーの編集内容が反映されない。
> SkinConfigurationView: change to save skinHistory by commit()

- src/bms/player/beatoraja/select/MusicSelector.java
選曲画面のルートフォルダから選曲すると、NoSuchElementExceptionでbeatorajaが落ちる問題を修正。
問題発生PullRequest #426
1. ランチャーのリソースタブのBMS Pathに、BMSファイルを直下に含むフォルダを指定する。
2. beatoraja起動後、選曲画面のルートフォルダから任意のBMSを選曲する。
3. `NoSuchElementException: Queue is empty.`が発生し、beatorajaが落ちる。
発生時ログ
```
Exception in thread "LWJGL Application" java.util.NoSuchElementException: Queue is empty.
at com.badlogic.gdx.utils.Queue.last(Queue.java:277)
at bms.player.beatoraja.select.MusicSelector.render(Unknown Source)
at bms.player.beatoraja.MainController.render(Unknown Source)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127) 
```
> Fix "NoSuchElementException: Queue is empty." in  MusicSelector

- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
* BMSONでチャンネル名が空の（無音の）チャンネルのノーツでデフォルト地雷音が鳴る問題を修正しました。
* 名前が空のチャンネルは、無音ノーツとしてだけでなく曲の終了タイミングの制御のためにBGレーンに配置されていることもあります。（BMS形式からBMSONに変換したときにこのバグに遭遇しました。）
* 再現例：
```json
{"bga":{"bga_events":[],"bga_header":[],"layer_events":[],"poor_events":[]},"bpm_events":[],"info":{"artist":"artist","back_image":"","banner_image":"","chart_name":"BMSON test","eyecatch_image":"","genre":"genre","init_bpm":140,"judge_rank":100,"level":3,"mode_hint":"beat-7k","preview_music":"","resolution":240,"subartists":[],"subtitle":"","title":"nameless channel issue demo","title_image":"","total":100},"lines":[{"y":0},{"y":960},{"y":1920},{"y":2880},{"y":3840},{"y":4800},{"y":5760},{"y":6720},{"y":7680},{"y":8640},{"y":9600},{"y":10560}],"sound_channels":[{"name":"","notes":[{"c":false,"l":0,"x":8,"y":960},{"c":false, …
```
> Fix: nameless channels in BMSON make default landmine sound

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
When a BGA file has an incompatible audio track, the BGA will not play.
It can also cause a thread leak issue (which makes beatoraja create many threads that will never be closed, causing the game to slow down significantly).
This happens with the BGA for [Shiny☆Strike!!!](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=6&event=133) from BOFXVI.
However, the BGA has been fixed by the artist in the newest version of the song download.
The old version of the BGA (which causes the issue) can be downloaded here: [shinystrike_bga.zip](https://github.com/exch-bms2/beatoraja/files/6526779/shinystrike_bga.zip)
- **Note:** The BGA has been trimmed to only the first 15 seconds. This is enough to reproduce the issue.
Codec information:
```
Input #0, asf, from '_bga.wmv':
Metadata: …
```
> Fix BGA + thread leak issue when audio track is incompatible in BGA

- src/bms/player/beatoraja/pattern/LaneShuffleModifier.java
`noMurioshiLaneShuffle` method used in RANDOM_EX for 9k, was incredibly complex and difficult to analyze. Nine nested for loops were used to generate all possible random lane permutations, with a lot of iterations simply discarded. It then checked for any impossible chord combinations for 9k.
It is now implemented using Heap's algorithm, in an extracted method that returns permutations with no murioshi chords.
There's a lot of possibilities for further optimization, such as ignoring mirrored permutations, but it's a major start.
> Refactor of no murioshi lane shuffle feature

- src/bms/player/beatoraja/skin/lua/MainStateAccessor.java
luaスキンで呼び出せる`main_state`モジュールに、イベントの現在の状態のインデックスを返す`event_index(id)`関数を追加
例:
ゲージにEXHARDを選択している場合、ゲージのインデックス順は以下の通りなので、main_state.event_index(40)は4を返します。
- 0 ASSITED EASY
- 1 EASY
- 2 NORMAL
- 3 HARD
- 4 EXHARD
- 5 HAZARD
> Add event_index to main_state

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/StringPropertyFactory.java
以下の2つのString Propertyを追加
- STRING_VERSION: beatorajaのバージョンを表示 (例: "beatorja 0.8.3")
- STRING_IR_NAME: プライマリIRの名前を表示 (例: "mocha", "MinIR")
懸念点
- STRING_VERSIONで返される文字列の"beatoraja "部分は含むべきか
- STRING_IR_NAMEは開発環境だとIRに繋げないので正式にはテストできていません
- プロパティ番号は適切か(とりあえず少し離した番号を割り当てました)
> Add string properties for VERSION and IR_NAME

- src/bms/player/beatoraja/play/JudgeManager.java
地雷ノートを踏んだ時に地雷爆発音が再生されるよう修正
- 地雷ノートの爆発音の再生タイミングは、通常ノートや不可視ノートなどと同じだった
- そのため、地雷ノートを踏んだ時(地雷ノートが判定ラインを通過するタイミングで、該当するキーを押下している時)は爆発音が再生されなかった
> Fix playing timing of mine explotion sound

- src/bms/player/beatoraja/PlayerResource.java
- src/bms/player/beatoraja/audio/AbstractAudioDriver.java
デフォルト地雷爆発音(defaultsound/landmine.wav)が再プレイ時に再生されない問題を修正
発生タイミング
- プラクティスモードでの再プレイ時
- クイックリトライ時
> Fix the default mine explotion sound not playing when replaying

- skin/default/skinselect/skinselectmain.lua
デフォルトのSKIN SELECTスキン(`beatoraja default (lua)`)で24KEY(と2つのバリエーション)が選択できない問題を修正しました。選択後に各項目が変更できることを確認済みです。
参考：
https://github.com/exch-bms2/beatoraja/blob/89e6ab145468461cffe1cf7a3b3a336c3c9d8dd8/src/bms/player/beatoraja/skin/SkinProperty.java#L899-L901
https://github.com/exch-bms2/beatoraja/blob/89e6ab145468461cffe1cf7a3b3a336c3c9d8dd8/src/bms/player/beatoraja/skin/SkinProperty.java#L928-L930
※スキンのみの不具合なので起動前の設定画面では正常に選択できます
> Fix: 24KEY cannot be selected by default SKIN SELECT skin

- src/bms/player/beatoraja/RandomCourseData.java
- src/bms/player/beatoraja/RandomStageData.java
- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/MusicSelector.java
- src/bms/player/beatoraja/select/bar/RandomCourseBar.java
- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
- src/bms/player/beatoraja/skin/property/StringPropertyFactory.java
ランダムコースを実装しました。ステージの曲を指定した検索条件でランダムに決定するコースです。
動作としてはLR2のRANDOM MIX(NONSTOPなし)のイメージです。RANDOM MIXと違い、ステージ毎に曲の検索条件を設定できます。
コース定義はカスタムフォルダ(`folder/default.json`)に記述し、曲の検索条件もカスタムフォルダと同様の形式のsqlで書きます。
folder/default.json
```json
{
"name":"Folder Name",
"rcourse":[
{
"name": "RandomCourse Name",
"stage": [
{
"title": "Stage 1",
"sql": "sql": "song.mode = 7 AND level = 9"
},
{
"title": "Stage 2",
"sql": "sql": "song.mode = 7 AND level = 10"
},
{
"title": "Stage 3",
"sql": "sql": "song.mode = 7 AND level = 11"
},
{
"title": "Stage 4",
"sql": "sql": "song.mode = 7 AND level = 12"
},
],
"constraint": [
"MIRROR",
"GAUGE_LR2",
],
"rconstraint": [
"DISTINCT",
],
"trophy": [
{
"name": "bronzemedal",
"missrate": 7.5,
"scorerate": 55
},
{
"name": "silvermedal",
"missrate": 5,
"scorerate": 70
},
{
"name": …
```
> Add RandomCourse

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
bmson譜面を考慮し、タグとFAVORITE保持処理に使用するプロパティマップのキーをmd5からsha256に修正
bmson譜面のレコードに付与されていたタグとFAVORITE情報が、楽曲読み込み/楽曲全更新時に他のbmson譜面のレコードにコピーされてしまう。
1. 任意のbmson譜面にFAVORITEを付ける
2. bmson譜面をリソースフォルダ内に追加する
3. 楽曲読み込みをする
4. 2で追加したbmson譜面に1で付与したFAVORITE情報がコピーされる
1. 任意のbmson譜面にFAVORITEを付ける
2. 楽曲全更新をする
3. 全てのbmson譜面に1で付与したFAVORITE情報がコピーされる
タグとFAVORITE保持処理に使用するプロパティマップのキーにmd5を使用していたため、md5が存在しないbmson譜面の保持処理時にキーが全て空文字`""`になり、他の更新対象のbmson譜面に値がコピーされてしまっていた。
> Fix key of property map from md5 to sha256 to support bmson

- src/bms/player/beatoraja/launcher/CourseEditorView.java
- src/bms/player/beatoraja/launcher/FolderEditorView.java
- src/bms/player/beatoraja/launcher/TableEditorView.java
This only affects the custom tables / custom courses tab in the beatoraja configuration.
Double-clicking a song in the search bar, custom course or custom table will open a dialog box that displays details of the chart/song. The details can be selected and copied with ctrl+c.
1. It was previously not possible to copy (ctrl+c) song titles and hashes out of custom courses and tables. This details panel allows easy copying of the chart hash and metadata. (this makes it easier to transfer a chart from one folder to another)
2. The "Open Folder" button can be used to open the song in explorer (similar to F3 in game)
3. At the bottom of the dialog, the custom table folders that the chart is in are listed. Now you can check if a chart is already in the custom table before adding it. It makes it …
> Display chart details on double-click in custom tables/courses tab in configuration.

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/MainState.java
- src/bms/player/beatoraja/decide/MusicDecide.java
- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/select/MusicSelector.java
-Introduced the shutdown() method to MainState class. It is called right before the prepare() method on a new state.
-Moved menu BGM playback start and stop to prepare() and shutdown() respectively to minimize audio desync.
> Menu BGM desync fixes

- src/bms/player/beatoraja/launcher/CourseEditorView.java
- src/bms/player/beatoraja/launcher/FolderEditorView.java
- src/bms/player/beatoraja/launcher/JavaFXUtils.java
#703 で実装された、設定画面のテーブルエディタで譜面をダブルクリックすると譜面詳細ダイアログが表示される機能において、テーブルのカラムヘッダーをダブルクリックした際には表示しないように修正（変更）しました。
実装の話ですが、ヘッダーの文字部分をクリックした場合、クリックイベントのターゲットがヘッダーではなくその子ノードのテキストになるので、単純な比較ではなくノードを探索するメソッドを生やして利用しています。
> Fixed table editor not displaying chart details when double-clicking on table column headers

- src/bms/player/beatoraja/select/bar/SongBar.java
Improves the performance of filtering out duplicates in the toSongBarArray function
This function is used when applying the custom folder filters, for example average density or LN percentage.
When filtering thousands of songs, these filters quickly become unusable due to the long processing time of the O(n^2) complexity
This also improves the performance of opening other directory folders
> fix toSongBarArray performance

- src/bms/player/beatoraja/play/PracticeConfiguration.java
PRACTICEモードのJUDGERANKの変更幅を10から1に変更しました。また、これに伴い、設定可能な下限値を10から1に変更しました。これによって、NORMAL判定(75)などの10の倍数ではないJUDGERANKを持つBMSをEASY(100)などに設定できない問題を解決します。
5ではなく1にしたのは、5の倍数ではないJUDGERANKを持つBMSがそれなりに存在するためです。実際に変更する頻度は低いと思われること、操作する際は高速で増減することからそこまで不便にはならないと思います。
> PracticeConfiguration : change JUDGERANK modifying step from 10 to 1

- src/bms/player/beatoraja/skin/property/FloatPropertyFactory.java
`FloatPropertyFactory` の各種レート `rate_xxx` をコースのスコアに対しても取得できるようにしました。
現状のままでもスキン側での計算は可能ですが、こちらのほうがより利用しやすくなると思います。
最大値はコースの全ステージ楽曲の合計ノーツ数で計算しています。
到達したステージまでで計算することも考えましたが、到達ステージが更新された場合にレートが落ちる可能性が高く不自然に感じられること、他の各種データが全ステージで計算されていることを考えると、同じようにする方が良いと判断しました。
> FloatPropertyFactory: Added support for course scores in rate_xxx

- src/bms/player/beatoraja/PlayDataAccessor.java
- src/bms/player/beatoraja/ScoreDataLogDatabaseAccessor.java
- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
Previously, the `scoreLog` was only updated and stored if there were **updates** compared to the old score. In other words, the result information of `newscore` was usually discarded within the `writeScoreData` function.
This PR modifies `writeScoreData` to save every result of BMS play.
- create `scoredatalogdb`
- fill in any missing values from `score` and the SongTrophies
- insert `newscore` into `scoredatalogdb`
- fix typos
This log will be a useful analytic resource for players within the beatoraja ecosystem.
It will be a helpful companion for AIR -GOD- KNOCK in particular.
> Save newscore data even if the score have no update

- src/bms/player/beatoraja/result/CourseResult.java
`CourseResult` クラスの `create()` メソッド内におけるスキン読み込みタイミングをメソッドの最後へ移動しました。
これにより、 `create()` 内で初期化が終わっていない値をLuaスキンの初期処理時に `main_state` で正常に参照できない問題が解決され、例えばコースリザルトのスコアに基づくスキン表示条件の複雑な制御などが可能になります。
従来のままでもスキンが実際に描画されるタイミングでは初期化が終わっているので、 `ref` の指定や `value` に渡した関数などによる参照は正常に動作していると思われます。
> Moved skin loading timing during initialization of COURSE RESULT to the end

- src/bms/player/beatoraja/result/SkinGaugeGraphObject.java
リザルト画面のゲージグラフの折れ線をグラフ領域の右端まで描画するように修正しました。
> Fixed to draw the gauge graph to the right end

- src/bms/player/beatoraja/select/BarSorter.java
選曲画面におけるソートでスコアレートの差が非常に小さい場合に正しい並び順にならないことがある問題を修正しました。
この原因は、比較用の値が整数同士で計算され小数部が切り捨てられること、ならびに差を比較結果として返した時に自動的にintにキャストされ小数部が切り捨てられることで比較関数の返値が0になるという問題でした。そこで、floatで計算した上で明示的に整数で返すように変更しました。
もしかするとパフォーマンス上の理由により意図的に精度を落としていたのかもしれませんが、スキンでスコアレートを小数点以下2桁まで%表示できる場合にそのレートと並びが食い違うケースを通常のゲームプレイの中で確認したため、精度を上げた方が良いと判断しました。変更後の処理の負荷に関しては問題ない範疇だと考えています。
a. (score: 1992 * 1000 / notes: 1428) = 1394.9579831932774 (69.74%)
b. (score: 2091 * 1000 / notes: 1500) = 1394 (69.70%)
> Fixed a sorting problem in SCORE_SORTER for score rates with very small differences

- src/bms/player/beatoraja/ScoreDataProperty.java
`ScoreDataProperty` 内の `rivalscore` と `rivalscorerate` の更新時に `rivalrateInt` と `rivalrateAfterDot` も更新するようにしました。今までは `ScoreDataProperty::setTargetScore` の呼び出し時のみ更新されていました。この変更により、選曲バーの幾つかの操作とライバルスコアの取得後に上記の値が更新されずスキンで正常に参照できなかった問題が解決します。
1. IRに接続した状態で、ターゲットスコアをIR関連にする
2. PLAYスキンを `rivalrateInt` と `rivalrateAfterDot` を参照する整数プロパティ(122と123など)が用いられたものに設定する
3. 選曲画面でランキングの取得前にIRのプレイ人数が1人以上の譜面を選曲し、プレイ画面に移行する
4. ターゲットスコアが1以上であるにもかかわらずレート表示が0.00%のようになっている
> Fix to also update rivalrateInt when updating rivalscore in ScoreDataProperty

- src/bms/player/beatoraja/ScoreDataProperty.java
- src/bms/player/beatoraja/play/TargetProperty.java
スコアランク (AAAなど) に関連する一部の計算処理を修正します。
nextrankの算出時、次のランクまでの差分の小数点以下の四捨五入を切り上げに修正しました。
例えば、1771ノーツの譜面のAランク下限スコアは `(1771 * 2) * (6 / 9) = 2361.3333333333335` です。そして「Aランクの下限以上 (Greater than or Equal)」の最小の整数は2362なので、スコア2361はA-1となります。従来は四捨五入だったのでA-0になり、それ以上(AAまで)計算されていませんでした。B(A+0)やAA(AAA+0)のような表記になることが稀にあるのはこれが原因です。
スコアランクのレートからターゲットスコアを算出する際に小数点以下の切り捨てを切り上げに修正しました。前項の例だとAランクのスコアが2361から2362になります。もっと確認しやすい例だと2000ノーツのAAAスコアが3555から3556になります。
> Fixed of score calculation process related to score ranks

- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
スキンの整数プロパティにはレーンカバーON/OFF時 × MIN/MAX/MAIN BPM時のDurationと緑数字を個別で得られるプロパティが1312~1327の範囲で用意されていますが、このDurationと緑数字が逆になっていた問題を修正しました。
> Fixed NUMBER_DURATION_LANECOVER_* duration and duration_green being reversed

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/StringPropertyFactory.java
スキンで選択中の楽曲のMD5ハッシュとSHA-256ハッシュを得る文字列プロパティを追加しました。楽曲の情報がない場合は空文字列になります。
コースのハッシュについては、コースデータ自体はハッシュを持たず、各IRなど用途ごとにハッシュの計算方法を定める形式のため対応していません（プレイ中に現在のステージの楽曲ハッシュを得ることは可能です）。
> Add SONG_HASH_MD5 and SONG_HASH_SHA256 property

- src/bms/player/beatoraja/play/JudgeManager.java
HCNを終端ノーツの手前でリリースした際に、終端ノーツの判定に関わらず音が消えてしまう問題の修正を行いました。
> fix: key volume change on HCN release

- src/bms/player/beatoraja/launcher/InputConfigurationView.java
- src/bms/player/beatoraja/select/BarRenderer.java
- src/bms/player/beatoraja/select/PreviewMusicProcessor.java
- src/bms/player/beatoraja/skin/SkinText.java
- src/bms/player/beatoraja/stream/command/StreamRequestCommand.java
Javaでは文字列の比較に比較演算子ではなく `String::equals` メソッドを用いることが強く推奨されているため、そのように修正しました。これは広く知られたbad practiceであるため理由の詳しい説明は省略します。なお、左辺にnullの可能性がある箇所は `Object.equals` を使用しています。
特に `SkinText::draw` メソッドのそれは、前回の描画と異なる文字列だった場合に実行される `prepareText` メソッドによって不要なはずの負荷を招くケースが非常に多いことが確認されました (ただし `SkinText` の実装のうち  `.fnt` ファイルを扱う `SkinTextBitmap` は `prepareText` メソッドの実装が空なので負荷はほぼない) 。
修正された中にはそのままでも問題ないと思われる箇所があったかもしれませんが、個々に区別するのは脆弱な方針であり、また今後の仕様変更や実行環境の違いによって不具合として顕在化する可能性があるため、一括で修正すべきと判断しました。
----
余談: 頻繁に実行されるなら比較演算子を使った方がいいというのも全くの間違いではないですが、それでも `String::equals` メソッドの実装を見ると大抵の場合（Liberica 17など）高速化のため最初に `==` で比較しているようなので、やはり `equals` メソッドを使うのが良いでしょう。
> Fixed bad string comparisons

- src/bms/player/beatoraja/MainLoader.java
Tiling window manager tries to move all the windows in the tile, the game shows skewed screen regardless of configured value.
Making the window not resizable will fix that issue, allowing the window to be positioned and sized as configured.
> Make the game window not resizable

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
When a single new BMS path is added in the launcher the directories under that path are not currently processed in parallel, resulting in slow (sometimes multiple hour long) process times. This uses a parallel stream instead of a regular stream to iterate over recursive directories and files under the added path instead of processing them sequentially.
This reopens #569, critically using the slightly faster parallelStream() interface of List over the slower stream.parallel().
I am aware that there had appeared to have been an issue resulting in the closure of #569:
> I've tried to implement same code, but it sometimes causes OutOfMemoryError. (Maybe too much threads)
_Originally posted by @exch-bms2 in https://github.com/exch-bms2/beatoraja/issues/569#issuecomment-724024485_
However after …
> Use parallelStream() to process directories when updating song data

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
Catch NPE on failed bms parse. Very rare but happens with some `bmson` charts, also added to `bm*` for posterity.
Will log the offending charts rather than an ambiguous NPE trace some function calls higher.
> Useful error message on failed bms parse

- src/bms/player/beatoraja/play/PracticeConfiguration.java
- src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java
- src/bms/player/beatoraja/skin/json/JsonSkin.java
- src/bms/player/beatoraja/skin/json/JsonSkinObjectLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2CourseResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java
- src/bms/player/beatoraja/skin/lr2/LR2SelectSkinLoader.java
Remove measure gaps for cleaner notegraphs. These typically appear heavily aliased in skins.
Before:
After:
Measures can still be distinguished by heights of different bars and colour within.
> Add noGapX to remove width gaps in note graphs

- src/bms/player/beatoraja/select/PreviewMusicProcessor.java
-The PreviewMusicProcessor class manages the playback of the song select menu music and the preview music.
-The very first instance of the defaultMusic playback that is scheduled at the start of the thread is not tracked.
-When using random menu bgm selection, skins without much animations and fast PCs, this can result in the PreviewThread not processing any requests and going straight to exit.
-At exit, the thread tries to stop the playback of a currently tracked music, but since the first playback is untracked, it fails to be stopped, resulting in overlaying BGM playback if you have random BGM selection.
-Fixed by making this first playback schedule trackable.
> Fix for the corrupted preview music playback

- src/bms/player/beatoraja/play/TargetProperty.java
ターゲットスコアがライバルまたはIR順位の場合、そのターゲットのランダム配置 (IndexType 61~63) の値が常に0になり、正常に取得できない問題を修正しました。
スコアが存在しない場合に設定される値0は `IDENTITY` (RANDOM OFF) と区別できませんが、対応するにせよしないにせよ、ここの変更で手を出す問題ではないと考えたため暫定的に0にしています。
> Fixed a problem where target options could not be referenced from rivals and IR

- src/bms/player/beatoraja/skin/SkinProperty.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
fix #795 
***
計算方法変更は既存への影響が広すぎるので、「それっぽい値」を逆計算して新規PROPとして渡すように修正。
定数名やprop numは暫定。
> Add IIDX SUD+ lane cover prop value.

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
動画のループ処理がリソースの開放と再取得を行っていたため、単純に先頭へシークするように変更し、パフォーマンスを改善しました。
> Improved video loop performance

- src/bms/player/beatoraja/play/bga/FFmpegProcessor.java
PR #801 (Improved video loop performance) にて、現在プロジェクトで依存関係にあるJavaCV v1.3.3で利用できないメソッド `grabber.setVideoFrameNumber(int)` (v1.4.1から利用可能) を用いていたため、互換性のあるメソッド `setFrameNumber(int)` を用いるように修正しました。
v1.3.3と最新版v1.5.10では `setFrameNumber(int)` の実装が少し異なりますが、どちらでも動作することを確認しています。
> Fixed compatibility issues with loop processing

- src/bms/player/beatoraja/config/KeyConfiguration.java
- src/bms/player/beatoraja/input/BMSPlayerInputProcessor.java
選曲画面で読み込まれた`ControllerConfig`の状態がそのまま残っているので、キーコンフィグおよびプレイにおいてコントローラがdisabledのままになっている。
`PlayerConfig.musicselectinput`が`0`(iidx sp)か`1`(pop'n)のとき、選曲画面でコントローラが1つしかenabledにならないので、その状態でキーコンフィグ設定やDPをプレイをしようとすると、2つ目以降のコントローラの入力を受け付けなくなる。
`PlayerConfig.musicselectinput`が`2`(iidx dp)でも、選曲画面でコントローラが2つしかenabledにならないので、コントローラが3つ以上接続されている場合、3つ目以降のコントローラにキーを設定できない。
The availabilities of controllers set in music select are not properly cleared and remain in keyconfig and play.
When` PlayerConfig.musicselectinput` is `0` (iidx sp) or `1` (pop'n), only one controller is enabled in music select, thus the other controllers are ignored in keyconfig or DP play.
Even when `PlayerConfig.musicselectinput` is `2` (iidx dp), just two controllers are enabled in music select, so you cannot assign keys to third or …
> fix controller availability in keyconfig and play state

- src/bms/player/beatoraja/play/BMSPlayer.java
コースモードで曲開始後1ノーツも処理せずにスタート+セレクト同時押しでプレイを停止すると、完走扱いになり、次の曲に進んでしまう。
when you press start and select button to quit without hitting any notes in course mode, it transits to `STATE_FINISHED` rather than `STATE_FAILED` and moves onto the next song.
- 1ノーツも処理せずに終了した場合`STATE_FAILED`になるようにする
- コースモードの時は1ノーツも処理していなくても`createScoreData()`が`null`を返却しないようにする
　
- make it transit to `STATE_FAILED` when quitting with no notes hit.
- make `createScoreData()` return non-null value in course mode even if no notes are hit
> fix stop play behavior in course mode

- src/bms/player/beatoraja/result/MusicResult.java
- src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
- src/bms/player/beatoraja/song/SongInformation.java
Since #LNMODE definition in BMS file overrides player's LN mode option, there are some issues. 
- skin property provides playerconfig value regardless of #LNMODE 
- note distribution graph also refers playerconfig and draws a weird one like:
check `BMSModel.getLnmode()` or `SongData.has*Note()` to see whether #LNMODE is defined
> fix some issues related to #LNMODE

- src/bms/player/beatoraja/ReplayData.java
一度のプレイ（リザルト）で複数のリプレイを保存する場合、1回目の後処理によって2回目以降にキー入力ログを正しく保存できなくなる問題を修正しました。
> Fixed an issue where replay keyinputs were not being saved correctly

- src/bms/player/beatoraja/result/CourseResult.java
- src/bms/player/beatoraja/result/MusicResult.java
- fix  #796 
wrap each iteration for `irSendStatus` instead of whole loop by try-catch and add more detailed logging in Music/Course Result.
> fix exception handling while sending score to IR

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/skin/Skin.java
デバッグ時の情報テキストの位置をpublic static finalで定義ました。
デバッグ時のみ、F1で表示される情報にスキン描画パフォーマンスカウンタを追加しました。
skinObjectのサブクラス毎にPrepare, Drawで分けて0.1μs単位で計測しています。
7つの数字は左から、オブジェクト数、Prepare時間、移動平均、最大、Draw時間、移動平均、最大
> add skin Paformance counter only if debug on.

- src/bms/player/beatoraja/MainController.java
- src/bms/player/beatoraja/skin/Skin.java
- src/bms/player/beatoraja/skin/SkinTimingVisualizer.java
今まではdrawが呼ばれるたびにPixmapからTextureを生成していたため、それがオーバーヘッドとなっていた。
判定位置表示ラインのTextureをあらかじめ生成し、SkinObject#drawでラインを描画することで描画パフォーマンスを向上させた。
TextureRegion数に変化なし。
> SkinTimingVisualizerの描画パフォーマンスを改善した

- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
- src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
CONSTANTオプションのオンオフ状態取得がプレイ画面 (BMSPlayer) でのOPTIONプロパティのみだったため、以下の変更を行いました。
- option(400) を選曲画面で利用可能にした
- event_index(400) を追加した
event_indexは他のプレイオプション同様、0がOFFで1がONです。使用例として、状態を表示しつつクリックで状態を切り替える画像ボタンは以下のようにして定義できます：
```lua
{ id = "constant", src = "options", x = 2000, y = 500, w = 150, h = 70, divy = 2, len = 2, ref = 400, act = 400 }
```
> Supported property to get constant option status with MusicSelector

- src/bms/player/beatoraja/PlayerConfig.java
- src/bms/player/beatoraja/play/TargetProperty.java
- issue #809 
reduced StaticTargetProperty rate by 1/27 (except for MAX), and added `RATE_MAX-` between `RATE_AAA+` and `MAX`
> fix StaticTargetProperty rate

- src/bms/player/beatoraja/skin/property/BooleanPropertyFactory.java
PLAYスキンの初期化時（ロード時）に `OPTON_CONSTANT` を参照できない問題を修正しました。
同様に初期化段階だと参照できないスキンプロパティが幾つかありますが、一括で対応するならスキンをロードするタイミングを変更する解決策が有力であること、またその解決策を採用する場合は慎重な動作確認が必要なことから、今回は一旦0.8.8新規オプションの `OPTION_CONSTANT` のみの修正となっています。
> Fixed problem where CONSTANT could not be referenced when initializing the PLAY skin

- src/bms/player/beatoraja/AudioConfig.java
デフォルト128だと発音できないBMSが増えてきたのでデフォルト値を修正
> 同時発音数のデフォルトを修正

- src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
プレビュー音声のファイルパスが変わった時に、bmsファイル自体の更新が無くても、`song` テーブル を更新するようにした。
This PR makes beatoraja update `preview` column on `song` table when preview file path is changed (even bms file is not modified), closing #827.
- #827
> update song table on preview file path change 
